import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const sourceUrl =
  "https://zh.wikisource.org/wiki/%E5%91%A8%E5%85%AC%E8%A7%A3%E5%A4%A2";
const rawUrl =
  "https://zh.wikisource.org/w/index.php?title=%E5%91%A8%E5%85%AC%E8%A7%A3%E5%A4%A2&action=raw";
const outputPath = path.resolve("server/rag/zhougongCorpus.generated.ts");

interface ParsedEntry {
  id: string;
  category: string;
  original: string;
}

const response = await fetch(rawUrl);
if (!response.ok) {
  throw new Error(`Failed to fetch Wikisource raw text: ${response.status}`);
}

const raw = await response.text();
const entries = parseWikisourceRaw(raw);

await mkdir(path.dirname(outputPath), { recursive: true });
await writeFile(outputPath, renderCorpusModule(entries), "utf8");

console.log(`Generated ${entries.length} Zhougong corpus entries at ${outputPath}`);

function parseWikisourceRaw(text: string): ParsedEntry[] {
  const entries: ParsedEntry[] = [];
  let category = "";

  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line) {
      continue;
    }

    const heading = line.match(/^==\s*(.+?)\s*==$/);
    if (heading) {
      category = heading[1].trim();
      continue;
    }

    if (!category || line.startsWith("{{") || line === "詩曰") {
      continue;
    }

    for (const part of line.split(/\u3000+| {2,}/)) {
      const original = part.trim();
      if (/^[\u4e00-\u9fff]{4,}$/.test(original)) {
        entries.push({
          id: `zhougong-${String(entries.length + 1).padStart(4, "0")}`,
          category,
          original
        });
      }
    }
  }

  return entries;
}

function renderCorpusModule(entries: ParsedEntry[]) {
  return `// Generated by scripts/buildZhougongCorpus.ts from Wikisource raw text.
// Source: ${sourceUrl}
// License: Wikisource text is available under CC BY-SA 4.0 unless otherwise noted;
// the underlying traditional text may be public domain depending on jurisdiction.

export const zhougongCorpus = ${JSON.stringify(entries, null, 2)} as const;
`;
}
