// Generated by scripts/buildZhougongCorpus.ts from Wikisource raw text.
// Source: https://zh.wikisource.org/wiki/%E5%91%A8%E5%85%AC%E8%A7%A3%E5%A4%A2
// License: Wikisource text is available under CC BY-SA 4.0 unless otherwise noted;
// the underlying traditional text may be public domain depending on jurisdiction.

export const zhougongCorpus = [
  {
    "id": "zhougong-0001",
    "category": "天地日月星辰",
    "original": "天門開貴人薦引"
  },
  {
    "id": "zhougong-0002",
    "category": "天地日月星辰",
    "original": "天光照主疾病除"
  },
  {
    "id": "zhougong-0003",
    "category": "天地日月星辰",
    "original": "天晴雨散百憂去"
  },
  {
    "id": "zhougong-0004",
    "category": "天地日月星辰",
    "original": "天明婦人生貴子"
  },
  {
    "id": "zhougong-0005",
    "category": "天地日月星辰",
    "original": "天門赤主有大起"
  },
  {
    "id": "zhougong-0006",
    "category": "天地日月星辰",
    "original": "仰面向天大富貴"
  },
  {
    "id": "zhougong-0007",
    "category": "天地日月星辰",
    "original": "乘龍上天大主貴"
  },
  {
    "id": "zhougong-0008",
    "category": "天地日月星辰",
    "original": "上天求妻兒女貴"
  },
  {
    "id": "zhougong-0009",
    "category": "天地日月星辰",
    "original": "天上取物位王侯"
  },
  {
    "id": "zhougong-0010",
    "category": "天地日月星辰",
    "original": "飛上天富貴大吉"
  },
  {
    "id": "zhougong-0011",
    "category": "天地日月星辰",
    "original": "登天上屋得高官"
  },
  {
    "id": "zhougong-0012",
    "category": "天地日月星辰",
    "original": "天裂有分國之憂"
  },
  {
    "id": "zhougong-0013",
    "category": "天地日月星辰",
    "original": "天星明主公卿至"
  },
  {
    "id": "zhougong-0014",
    "category": "天地日月星辰",
    "original": "天愈鐃益壽命吉"
  },
  {
    "id": "zhougong-0015",
    "category": "天地日月星辰",
    "original": "渡天河主有所吉"
  },
  {
    "id": "zhougong-0016",
    "category": "天地日月星辰",
    "original": "天地富所求皆得"
  },
  {
    "id": "zhougong-0017",
    "category": "天地日月星辰",
    "original": "天公使有大吉祥"
  },
  {
    "id": "zhougong-0018",
    "category": "天地日月星辰",
    "original": "日月初出家道昌"
  },
  {
    "id": "zhougong-0019",
    "category": "天地日月星辰",
    "original": "日月照身得重位"
  },
  {
    "id": "zhougong-0020",
    "category": "天地日月星辰",
    "original": "日月落憂沒父母"
  },
  {
    "id": "zhougong-0021",
    "category": "天地日月星辰",
    "original": "日月昏暗孕婦吉"
  },
  {
    "id": "zhougong-0022",
    "category": "天地日月星辰",
    "original": "日月欲出有官職"
  },
  {
    "id": "zhougong-0023",
    "category": "天地日月星辰",
    "original": "日月合會妻有子"
  },
  {
    "id": "zhougong-0024",
    "category": "天地日月星辰",
    "original": "日月啣山奴欺主"
  },
  {
    "id": "zhougong-0025",
    "category": "天地日月星辰",
    "original": "負抱日月貴侯王"
  },
  {
    "id": "zhougong-0026",
    "category": "天地日月星辰",
    "original": "吞日月當生貴子"
  },
  {
    "id": "zhougong-0027",
    "category": "天地日月星辰",
    "original": "禮拜日月大吉昌"
  },
  {
    "id": "zhougong-0028",
    "category": "天地日月星辰",
    "original": "日光入屋官位至"
  },
  {
    "id": "zhougong-0029",
    "category": "天地日月星辰",
    "original": "日初出無雲大吉"
  },
  {
    "id": "zhougong-0030",
    "category": "天地日月星辰",
    "original": "日出有光有好事"
  },
  {
    "id": "zhougong-0031",
    "category": "天地日月星辰",
    "original": "雲開日出凶事散"
  },
  {
    "id": "zhougong-0032",
    "category": "天地日月星辰",
    "original": "日入懷貴子月女"
  },
  {
    "id": "zhougong-0033",
    "category": "天地日月星辰",
    "original": "拜星月燒香大吉"
  },
  {
    "id": "zhougong-0034",
    "category": "天地日月星辰",
    "original": "雲忽遮日有陰私"
  },
  {
    "id": "zhougong-0035",
    "category": "天地日月星辰",
    "original": "星入懷主生貴子"
  },
  {
    "id": "zhougong-0036",
    "category": "天地日月星辰",
    "original": "星落有病及官事"
  },
  {
    "id": "zhougong-0037",
    "category": "天地日月星辰",
    "original": "星列行主添奴婢"
  },
  {
    "id": "zhougong-0038",
    "category": "天地日月星辰",
    "original": "持執星宿大富貴"
  },
  {
    "id": "zhougong-0039",
    "category": "天地日月星辰",
    "original": "流星不落主移居"
  },
  {
    "id": "zhougong-0040",
    "category": "天地日月星辰",
    "original": "巡天摩星位公卿"
  },
  {
    "id": "zhougong-0041",
    "category": "天地日月星辰",
    "original": "雲起四方交易吉"
  },
  {
    "id": "zhougong-0042",
    "category": "天地日月星辰",
    "original": "五色雲主大吉昌"
  },
  {
    "id": "zhougong-0043",
    "category": "天地日月星辰",
    "original": "雲赤白吉青黑凶"
  },
  {
    "id": "zhougong-0044",
    "category": "天地日月星辰",
    "original": "見浮雲作事不成"
  },
  {
    "id": "zhougong-0045",
    "category": "天地日月星辰",
    "original": "雲霧遮事大吉利"
  },
  {
    "id": "zhougong-0046",
    "category": "天地日月星辰",
    "original": "黑雲至地時氣病"
  },
  {
    "id": "zhougong-0047",
    "category": "天地日月星辰",
    "original": "霜雪降主事不成"
  },
  {
    "id": "zhougong-0048",
    "category": "天地日月星辰",
    "original": "雪下及時大吉利"
  },
  {
    "id": "zhougong-0049",
    "category": "天地日月星辰",
    "original": "雪落身上萬事成"
  },
  {
    "id": "zhougong-0050",
    "category": "天地日月星辰",
    "original": "雪不沾身主孝服"
  },
  {
    "id": "zhougong-0051",
    "category": "天地日月星辰",
    "original": "雪落家庭主喪事"
  },
  {
    "id": "zhougong-0052",
    "category": "天地日月星辰",
    "original": "陰雨晦暗主凶事"
  },
  {
    "id": "zhougong-0053",
    "category": "天地日月星辰",
    "original": "行路逢雨有酒食"
  },
  {
    "id": "zhougong-0054",
    "category": "天地日月星辰",
    "original": "雷霆作事官位至"
  },
  {
    "id": "zhougong-0055",
    "category": "天地日月星辰",
    "original": "雷聲恐怕移居吉"
  },
  {
    "id": "zhougong-0056",
    "category": "天地日月星辰",
    "original": "雷從地震主志遂"
  },
  {
    "id": "zhougong-0057",
    "category": "天地日月星辰",
    "original": "身被霹靂主富貴"
  },
  {
    "id": "zhougong-0058",
    "category": "天地日月星辰",
    "original": "電光照身有吉慶"
  },
  {
    "id": "zhougong-0059",
    "category": "天地日月星辰",
    "original": "赤虹見吉黑虹凶"
  },
  {
    "id": "zhougong-0060",
    "category": "天地日月星辰",
    "original": "霞滿天百事歡悅"
  },
  {
    "id": "zhougong-0061",
    "category": "天地日月星辰",
    "original": "狂風大雨人死亡"
  },
  {
    "id": "zhougong-0062",
    "category": "天地日月星辰",
    "original": "風吹人衣主疾病"
  },
  {
    "id": "zhougong-0063",
    "category": "天地日月星辰",
    "original": "忽大風國有號令"
  },
  {
    "id": "zhougong-0064",
    "category": "天地日月星辰",
    "original": "風如吼主遠信至"
  },
  {
    "id": "zhougong-0065",
    "category": "地理山石樹木",
    "original": "地動主遷官位吉"
  },
  {
    "id": "zhougong-0066",
    "category": "地理山石樹木",
    "original": "地裂主疾病大凶"
  },
  {
    "id": "zhougong-0067",
    "category": "地理山石樹木",
    "original": "修平田地大吉昌"
  },
  {
    "id": "zhougong-0068",
    "category": "地理山石樹木",
    "original": "地高下不平主病"
  },
  {
    "id": "zhougong-0069",
    "category": "地理山石樹木",
    "original": "臥於石上主大吉"
  },
  {
    "id": "zhougong-0070",
    "category": "地理山石樹木",
    "original": "地中黑氣上主凶"
  },
  {
    "id": "zhougong-0071",
    "category": "地理山石樹木",
    "original": "運石入家主富貴"
  },
  {
    "id": "zhougong-0072",
    "category": "地理山石樹木",
    "original": "石上得利祿大吉"
  },
  {
    "id": "zhougong-0073",
    "category": "地理山石樹木",
    "original": "盤石安穩無憂疑"
  },
  {
    "id": "zhougong-0074",
    "category": "地理山石樹木",
    "original": "登岩抱石官職遷"
  },
  {
    "id": "zhougong-0075",
    "category": "地理山石樹木",
    "original": "手弄小石生貴子"
  },
  {
    "id": "zhougong-0076",
    "category": "地理山石樹木",
    "original": "身入土中百事吉"
  },
  {
    "id": "zhougong-0077",
    "category": "地理山石樹木",
    "original": "自身取土被恥辱"
  },
  {
    "id": "zhougong-0078",
    "category": "地理山石樹木",
    "original": "昇山落地主失位"
  },
  {
    "id": "zhougong-0079",
    "category": "地理山石樹木",
    "original": "上山恐怕祿位至"
  },
  {
    "id": "zhougong-0080",
    "category": "地理山石樹木",
    "original": "上山毀壞主凶惡"
  },
  {
    "id": "zhougong-0081",
    "category": "地理山石樹木",
    "original": "遊看高山春夏吉"
  },
  {
    "id": "zhougong-0082",
    "category": "地理山石樹木",
    "original": "行走上坡病思除"
  },
  {
    "id": "zhougong-0083",
    "category": "地理山石樹木",
    "original": "居住高山有喜事"
  },
  {
    "id": "zhougong-0084",
    "category": "地理山石樹木",
    "original": "山行得財有福緣"
  },
  {
    "id": "zhougong-0085",
    "category": "地理山石樹木",
    "original": "抱物上山孕貴子"
  },
  {
    "id": "zhougong-0086",
    "category": "地理山石樹木",
    "original": "山中農稼衣食豐"
  },
  {
    "id": "zhougong-0087",
    "category": "地理山石樹木",
    "original": "枯木再發子孫興"
  },
  {
    "id": "zhougong-0088",
    "category": "地理山石樹木",
    "original": "堂上地陷主母憂"
  },
  {
    "id": "zhougong-0089",
    "category": "地理山石樹木",
    "original": "園林茂盛大吉利"
  },
  {
    "id": "zhougong-0090",
    "category": "地理山石樹木",
    "original": "樹木枯死宅不安"
  },
  {
    "id": "zhougong-0091",
    "category": "地理山石樹木",
    "original": "林中坐臥病欲痊"
  },
  {
    "id": "zhougong-0092",
    "category": "地理山石樹木",
    "original": "樹木凋零主人凶"
  },
  {
    "id": "zhougong-0093",
    "category": "地理山石樹木",
    "original": "林中樹生添貴子"
  },
  {
    "id": "zhougong-0094",
    "category": "地理山石樹木",
    "original": "種植樹木大吉昌"
  },
  {
    "id": "zhougong-0095",
    "category": "地理山石樹木",
    "original": "登大樹名利顯揚"
  },
  {
    "id": "zhougong-0096",
    "category": "地理山石樹木",
    "original": "上樹忽折有死傷"
  },
  {
    "id": "zhougong-0097",
    "category": "地理山石樹木",
    "original": "與人分花主分散"
  },
  {
    "id": "zhougong-0098",
    "category": "地理山石樹木",
    "original": "枯木開花子孫興"
  },
  {
    "id": "zhougong-0099",
    "category": "地理山石樹木",
    "original": "大樹落人屋上吉"
  },
  {
    "id": "zhougong-0100",
    "category": "地理山石樹木",
    "original": "立樹下貴人庇蔭"
  },
  {
    "id": "zhougong-0101",
    "category": "地理山石樹木",
    "original": "樹生堂上父母憂"
  },
  {
    "id": "zhougong-0102",
    "category": "地理山石樹木",
    "original": "大樹忽折主凶惡"
  },
  {
    "id": "zhougong-0103",
    "category": "地理山石樹木",
    "original": "擔木來家得財喜"
  },
  {
    "id": "zhougong-0104",
    "category": "地理山石樹木",
    "original": "砍伐大樹多得財"
  },
  {
    "id": "zhougong-0105",
    "category": "地理山石樹木",
    "original": "草木茂盛家道興"
  },
  {
    "id": "zhougong-0106",
    "category": "地理山石樹木",
    "original": "門中生果樹有子"
  },
  {
    "id": "zhougong-0107",
    "category": "地理山石樹木",
    "original": "松生腹上位三公"
  },
  {
    "id": "zhougong-0108",
    "category": "地理山石樹木",
    "original": "家中生松事轉豐"
  },
  {
    "id": "zhougong-0109",
    "category": "地理山石樹木",
    "original": "家中生柏多吉利"
  },
  {
    "id": "zhougong-0110",
    "category": "地理山石樹木",
    "original": "庭前竹木喜重重"
  },
  {
    "id": "zhougong-0111",
    "category": "地理山石樹木",
    "original": "楓生屋上百事遂"
  },
  {
    "id": "zhougong-0112",
    "category": "地理山石樹木",
    "original": "蘭生庭前主添孫"
  },
  {
    "id": "zhougong-0113",
    "category": "地理山石樹木",
    "original": "果林中行主得財"
  },
  {
    "id": "zhougong-0114",
    "category": "地理山石樹木",
    "original": "入菜園中大發財"
  },
  {
    "id": "zhougong-0115",
    "category": "地理山石樹木",
    "original": "桑生井上主有憂"
  },
  {
    "id": "zhougong-0116",
    "category": "地理山石樹木",
    "original": "果樹多熟子孫安"
  },
  {
    "id": "zhougong-0117",
    "category": "地理山石樹木",
    "original": "折筍到家女有子"
  },
  {
    "id": "zhougong-0118",
    "category": "地理山石樹木",
    "original": "見筍者主添子孫"
  },
  {
    "id": "zhougong-0119",
    "category": "地理山石樹木",
    "original": "掃地除糞家欲破"
  },
  {
    "id": "zhougong-0120",
    "category": "地理山石樹木",
    "original": "糞土堆者錢財聚"
  },
  {
    "id": "zhougong-0121",
    "category": "身體面目齒髮",
    "original": "自身白衣人所謀"
  },
  {
    "id": "zhougong-0122",
    "category": "身體面目齒髮",
    "original": "梳頭洗面百憂去"
  },
  {
    "id": "zhougong-0123",
    "category": "身體面目齒髮",
    "original": "身拜尊長大吉昌"
  },
  {
    "id": "zhougong-0124",
    "category": "身體面目齒髮",
    "original": "身上汗出主凶惡"
  },
  {
    "id": "zhougong-0125",
    "category": "身體面目齒髮",
    "original": "身病蟲生得軍職"
  },
  {
    "id": "zhougong-0126",
    "category": "身體面目齒髮",
    "original": "身上蟲行病患安"
  },
  {
    "id": "zhougong-0127",
    "category": "身體面目齒髮",
    "original": "繩索繫身長命吉"
  },
  {
    "id": "zhougong-0128",
    "category": "身體面目齒髮",
    "original": "枷鎖臨身病欲來"
  },
  {
    "id": "zhougong-0129",
    "category": "身體面目齒髮",
    "original": "身成肥瘦皆為凶"
  },
  {
    "id": "zhougong-0130",
    "category": "身體面目齒髮",
    "original": "面對官者主大吉"
  },
  {
    "id": "zhougong-0131",
    "category": "身體面目齒髮",
    "original": "露體無衣大吉利"
  },
  {
    "id": "zhougong-0132",
    "category": "身體面目齒髮",
    "original": "婦人披頭有私情"
  },
  {
    "id": "zhougong-0133",
    "category": "身體面目齒髮",
    "original": "頭白主長命大吉"
  },
  {
    "id": "zhougong-0134",
    "category": "身體面目齒髮",
    "original": "頭生兩角有爭競"
  },
  {
    "id": "zhougong-0135",
    "category": "身體面目齒髮",
    "original": "頭禿髮落皆凶事"
  },
  {
    "id": "zhougong-0136",
    "category": "身體面目齒髮",
    "original": "面生瘡黑主子凶"
  },
  {
    "id": "zhougong-0137",
    "category": "身體面目齒髮",
    "original": "頭鬚白落憂子孫"
  },
  {
    "id": "zhougong-0138",
    "category": "身體面目齒髮",
    "original": "頭鬚再生主長命"
  },
  {
    "id": "zhougong-0139",
    "category": "身體面目齒髮",
    "original": "沐浴遷官疾病除"
  },
  {
    "id": "zhougong-0140",
    "category": "身體面目齒髮",
    "original": "洗手洗足舊病除"
  },
  {
    "id": "zhougong-0141",
    "category": "身體面目齒髮",
    "original": "照鏡明吉暗者凶"
  },
  {
    "id": "zhougong-0142",
    "category": "身體面目齒髮",
    "original": "破鏡照人主分散"
  },
  {
    "id": "zhougong-0143",
    "category": "身體面目齒髮",
    "original": "手足膿血出大吉"
  },
  {
    "id": "zhougong-0144",
    "category": "身體面目齒髮",
    "original": "屎尿污人大吉亨"
  },
  {
    "id": "zhougong-0145",
    "category": "身體面目齒髮",
    "original": "露頭披髮主人謀"
  },
  {
    "id": "zhougong-0146",
    "category": "身體面目齒髮",
    "original": "披髮蓋面官訟至"
  },
  {
    "id": "zhougong-0147",
    "category": "身體面目齒髮",
    "original": "剃頭剪髮家內凶"
  },
  {
    "id": "zhougong-0148",
    "category": "身體面目齒髮",
    "original": "眉與髮齊祿位至"
  },
  {
    "id": "zhougong-0149",
    "category": "身體面目齒髮",
    "original": "齒自落者父母凶"
  },
  {
    "id": "zhougong-0150",
    "category": "身體面目齒髮",
    "original": "齒落更生子孫興"
  },
  {
    "id": "zhougong-0151",
    "category": "冠帶衣服鞋襪",
    "original": "戴官登車官欲遷"
  },
  {
    "id": "zhougong-0152",
    "category": "冠帶衣服鞋襪",
    "original": "自戴襆頭巾帽吉"
  },
  {
    "id": "zhougong-0153",
    "category": "冠帶衣服鞋襪",
    "original": "簪冠登台職位遷"
  },
  {
    "id": "zhougong-0154",
    "category": "冠帶衣服鞋襪",
    "original": "貴人與之衣冠吉"
  },
  {
    "id": "zhougong-0155",
    "category": "冠帶衣服鞋襪",
    "original": "新換衣冠祿位至"
  },
  {
    "id": "zhougong-0156",
    "category": "冠帶衣服鞋襪",
    "original": "燒毀冠帽欲更官"
  },
  {
    "id": "zhougong-0157",
    "category": "冠帶衣服鞋襪",
    "original": "失去冠帽去退職"
  },
  {
    "id": "zhougong-0158",
    "category": "冠帶衣服鞋襪",
    "original": "拾得官帶祿位至"
  },
  {
    "id": "zhougong-0159",
    "category": "冠帶衣服鞋襪",
    "original": "與人公服主得職"
  },
  {
    "id": "zhougong-0160",
    "category": "冠帶衣服鞋襪",
    "original": "人與公服加官職"
  },
  {
    "id": "zhougong-0161",
    "category": "冠帶衣服鞋襪",
    "original": "女著冠帶主生子"
  },
  {
    "id": "zhougong-0162",
    "category": "冠帶衣服鞋襪",
    "original": "洗笏染服新官來"
  },
  {
    "id": "zhougong-0163",
    "category": "冠帶衣服鞋襪",
    "original": "執笏見貴人大吉"
  },
  {
    "id": "zhougong-0164",
    "category": "冠帶衣服鞋襪",
    "original": "笏硫憂凶三不祥"
  },
  {
    "id": "zhougong-0165",
    "category": "冠帶衣服鞋襪",
    "original": "與人笏綬主官遷"
  },
  {
    "id": "zhougong-0166",
    "category": "冠帶衣服鞋襪",
    "original": "腰帶者主官至吉"
  },
  {
    "id": "zhougong-0167",
    "category": "冠帶衣服鞋襪",
    "original": "文書用印有名聲"
  },
  {
    "id": "zhougong-0168",
    "category": "冠帶衣服鞋襪",
    "original": "帶印主妻生貴子"
  },
  {
    "id": "zhougong-0169",
    "category": "冠帶衣服鞋襪",
    "original": "著新袍主添妻妾"
  },
  {
    "id": "zhougong-0170",
    "category": "冠帶衣服鞋襪",
    "original": "著錦繡衣子孫榮"
  },
  {
    "id": "zhougong-0171",
    "category": "冠帶衣服鞋襪",
    "original": "洗染衣服皆大吉"
  },
  {
    "id": "zhougong-0172",
    "category": "冠帶衣服鞋襪",
    "original": "披蓑衣主大恩至"
  },
  {
    "id": "zhougong-0173",
    "category": "冠帶衣服鞋襪",
    "original": "被油污衣大恩澤"
  },
  {
    "id": "zhougong-0174",
    "category": "冠帶衣服鞋襪",
    "original": "衣服忽破妻外心"
  },
  {
    "id": "zhougong-0175",
    "category": "冠帶衣服鞋襪",
    "original": "新衣攢米百事凶"
  },
  {
    "id": "zhougong-0176",
    "category": "冠帶衣服鞋襪",
    "original": "與人衣服主患至"
  },
  {
    "id": "zhougong-0177",
    "category": "冠帶衣服鞋襪",
    "original": "裁衣著孛衣皆吉"
  },
  {
    "id": "zhougong-0178",
    "category": "冠帶衣服鞋襪",
    "original": "衣帶自解百事吉"
  },
  {
    "id": "zhougong-0179",
    "category": "冠帶衣服鞋襪",
    "original": "著黃衣皂衣皆吉"
  },
  {
    "id": "zhougong-0180",
    "category": "冠帶衣服鞋襪",
    "original": "著白衣主有人請"
  },
  {
    "id": "zhougong-0181",
    "category": "冠帶衣服鞋襪",
    "original": "著青衣神人助力"
  },
  {
    "id": "zhougong-0182",
    "category": "冠帶衣服鞋襪",
    "original": "著藍繡衣妻大利"
  },
  {
    "id": "zhougong-0183",
    "category": "冠帶衣服鞋襪",
    "original": "眾人著紫主情獘"
  },
  {
    "id": "zhougong-0184",
    "category": "冠帶衣服鞋襪",
    "original": "與人著青家人散"
  },
  {
    "id": "zhougong-0185",
    "category": "冠帶衣服鞋襪",
    "original": "眾人著白主官事"
  },
  {
    "id": "zhougong-0186",
    "category": "冠帶衣服鞋襪",
    "original": "眾人著緋大吉利"
  },
  {
    "id": "zhougong-0187",
    "category": "冠帶衣服鞋襪",
    "original": "妻著夫衣生貴子"
  },
  {
    "id": "zhougong-0188",
    "category": "冠帶衣服鞋襪",
    "original": "女子著衣平無事"
  },
  {
    "id": "zhougong-0189",
    "category": "冠帶衣服鞋襪",
    "original": "與人共衣妻私情"
  },
  {
    "id": "zhougong-0190",
    "category": "冠帶衣服鞋襪",
    "original": "失卻衣服妻難產"
  },
  {
    "id": "zhougong-0191",
    "category": "冠帶衣服鞋襪",
    "original": "好被自蓋得富貴"
  },
  {
    "id": "zhougong-0192",
    "category": "冠帶衣服鞋襪",
    "original": "人著己履妻有私"
  },
  {
    "id": "zhougong-0193",
    "category": "冠帶衣服鞋襪",
    "original": "得靴鞋主奴婢吉"
  },
  {
    "id": "zhougong-0194",
    "category": "冠帶衣服鞋襪",
    "original": "失履主奴婢逃走"
  },
  {
    "id": "zhougong-0195",
    "category": "冠帶衣服鞋襪",
    "original": "脫靴束帶主有凶"
  },
  {
    "id": "zhougong-0196",
    "category": "冠帶衣服鞋襪",
    "original": "鞋破子孫妻妾病"
  },
  {
    "id": "zhougong-0197",
    "category": "冠帶衣服鞋襪",
    "original": "著麻鞋百事和合"
  },
  {
    "id": "zhougong-0198",
    "category": "冠帶衣服鞋襪",
    "original": "新授官爵主貴子"
  },
  {
    "id": "zhougong-0199",
    "category": "冠帶衣服鞋襪",
    "original": "乞得鞋履人助力"
  },
  {
    "id": "zhougong-0200",
    "category": "冠帶衣服鞋襪",
    "original": "木履脫時己出厄"
  },
  {
    "id": "zhougong-0201",
    "category": "刀劍旌節鐘鼓",
    "original": "君王對仗有異吉"
  },
  {
    "id": "zhougong-0202",
    "category": "刀劍旌節鐘鼓",
    "original": "旌旂有龍大吉利"
  },
  {
    "id": "zhougong-0203",
    "category": "刀劍旌節鐘鼓",
    "original": "抱旌節主貴人扶"
  },
  {
    "id": "zhougong-0204",
    "category": "刀劍旌節鐘鼓",
    "original": "旌劍引入山主凶"
  },
  {
    "id": "zhougong-0205",
    "category": "刀劍旌節鐘鼓",
    "original": "造旌蓋主大吉利"
  },
  {
    "id": "zhougong-0206",
    "category": "刀劍旌節鐘鼓",
    "original": "羽蓋蓋身主富貴"
  },
  {
    "id": "zhougong-0207",
    "category": "刀劍旌節鐘鼓",
    "original": "旂旛迎接大富貴"
  },
  {
    "id": "zhougong-0208",
    "category": "刀劍旌節鐘鼓",
    "original": "旗旛竟出主疾病"
  },
  {
    "id": "zhougong-0209",
    "category": "刀劍旌節鐘鼓",
    "original": "手持旌節有恩賞"
  },
  {
    "id": "zhougong-0210",
    "category": "刀劍旌節鐘鼓",
    "original": "白蓋覆身大吉利"
  },
  {
    "id": "zhougong-0211",
    "category": "刀劍旌節鐘鼓",
    "original": "見做新旌大吉利"
  },
  {
    "id": "zhougong-0212",
    "category": "刀劍旌節鐘鼓",
    "original": "與人分傘主分散"
  },
  {
    "id": "zhougong-0213",
    "category": "刀劍旌節鐘鼓",
    "original": "拔刀出行主大吉"
  },
  {
    "id": "zhougong-0214",
    "category": "刀劍旌節鐘鼓",
    "original": "得人刀主行人至"
  },
  {
    "id": "zhougong-0215",
    "category": "刀劍旌節鐘鼓",
    "original": "人與三刀作刺史"
  },
  {
    "id": "zhougong-0216",
    "category": "刀劍旌節鐘鼓",
    "original": "與人與斫大吉慶"
  },
  {
    "id": "zhougong-0217",
    "category": "刀劍旌節鐘鼓",
    "original": "被刀出血得酒食"
  },
  {
    "id": "zhougong-0218",
    "category": "刀劍旌節鐘鼓",
    "original": "折刀刺人主失利"
  },
  {
    "id": "zhougong-0219",
    "category": "刀劍旌節鐘鼓",
    "original": "刀斧自傷大吉利"
  },
  {
    "id": "zhougong-0220",
    "category": "刀劍旌節鐘鼓",
    "original": "得人刀斧祿位至"
  },
  {
    "id": "zhougong-0221",
    "category": "刀劍旌節鐘鼓",
    "original": "刀落水中妻妾亡"
  },
  {
    "id": "zhougong-0222",
    "category": "刀劍旌節鐘鼓",
    "original": "失落刀劍主破財"
  },
  {
    "id": "zhougong-0223",
    "category": "刀劍旌節鐘鼓",
    "original": "帶刀劍行有財利"
  },
  {
    "id": "zhougong-0224",
    "category": "刀劍旌節鐘鼓",
    "original": "磨刀劍鋒快大吉"
  },
  {
    "id": "zhougong-0225",
    "category": "刀劍旌節鐘鼓",
    "original": "與人刀劍皆主凶"
  },
  {
    "id": "zhougong-0226",
    "category": "刀劍旌節鐘鼓",
    "original": "劍在床頭大吉利"
  },
  {
    "id": "zhougong-0227",
    "category": "刀劍旌節鐘鼓",
    "original": "女人帶刀大吉慶"
  },
  {
    "id": "zhougong-0228",
    "category": "刀劍旌節鐘鼓",
    "original": "女人拔刀主有子"
  },
  {
    "id": "zhougong-0229",
    "category": "刀劍旌節鐘鼓",
    "original": "剪刀主分財之事"
  },
  {
    "id": "zhougong-0230",
    "category": "刀劍旌節鐘鼓",
    "original": "剪刀剪物主得財"
  },
  {
    "id": "zhougong-0231",
    "category": "刀劍旌節鐘鼓",
    "original": "剪刀折股妻妾亡"
  },
  {
    "id": "zhougong-0232",
    "category": "刀劍旌節鐘鼓",
    "original": "甲冑庇身主吉利"
  },
  {
    "id": "zhougong-0233",
    "category": "刀劍旌節鐘鼓",
    "original": "鎗槊主官位吉利"
  },
  {
    "id": "zhougong-0234",
    "category": "刀劍旌節鐘鼓",
    "original": "見軍兵散主有凶"
  },
  {
    "id": "zhougong-0235",
    "category": "刀劍旌節鐘鼓",
    "original": "鐘磐有聲遠人來"
  },
  {
    "id": "zhougong-0236",
    "category": "刀劍旌節鐘鼓",
    "original": "鐘豉大鳴福祿至"
  },
  {
    "id": "zhougong-0237",
    "category": "刀劍旌節鐘鼓",
    "original": "打鼓有聲遠人來"
  },
  {
    "id": "zhougong-0238",
    "category": "刀劍旌節鐘鼓",
    "original": "見鼓佳聲懽樂吉"
  },
  {
    "id": "zhougong-0239",
    "category": "刀劍旌節鐘鼓",
    "original": "見鼓不嗚凶必至"
  },
  {
    "id": "zhougong-0240",
    "category": "刀劍旌節鐘鼓",
    "original": "看放煙火百憂散"
  },
  {
    "id": "zhougong-0241",
    "category": "帝王文武呼召",
    "original": "帝王宣召有驚喜"
  },
  {
    "id": "zhougong-0242",
    "category": "帝王文武呼召",
    "original": "后妃呼召飲有疾"
  },
  {
    "id": "zhougong-0243",
    "category": "帝王文武呼召",
    "original": "太子召大喜吉利"
  },
  {
    "id": "zhougong-0244",
    "category": "帝王文武呼召",
    "original": "天子賜坐有財吉"
  },
  {
    "id": "zhougong-0245",
    "category": "帝王文武呼召",
    "original": "見老君言有仙分"
  },
  {
    "id": "zhougong-0246",
    "category": "帝王文武呼召",
    "original": "拜佛欲動大有財"
  },
  {
    "id": "zhougong-0247",
    "category": "帝王文武呼召",
    "original": "看火上陳事大吉"
  },
  {
    "id": "zhougong-0248",
    "category": "帝王文武呼召",
    "original": "神佛嗔怒皆不吉"
  },
  {
    "id": "zhougong-0249",
    "category": "帝王文武呼召",
    "original": "王侯並坐大吉利"
  },
  {
    "id": "zhougong-0250",
    "category": "帝王文武呼召",
    "original": "來見貴人不得凶"
  },
  {
    "id": "zhougong-0251",
    "category": "帝王文武呼召",
    "original": "與聖賢說話大吉"
  },
  {
    "id": "zhougong-0252",
    "category": "帝王文武呼召",
    "original": "使命入門大吉利"
  },
  {
    "id": "zhougong-0253",
    "category": "帝王文武呼召",
    "original": "白衣召作便死亡"
  },
  {
    "id": "zhougong-0254",
    "category": "帝王文武呼召",
    "original": "拜尊長者有吉慶"
  },
  {
    "id": "zhougong-0255",
    "category": "帝王文武呼召",
    "original": "先祖考言求食吉"
  },
  {
    "id": "zhougong-0256",
    "category": "帝王文武呼召",
    "original": "人云大好者即凶"
  },
  {
    "id": "zhougong-0257",
    "category": "帝王文武呼召",
    "original": "人云死者得長命"
  },
  {
    "id": "zhougong-0258",
    "category": "帝王文武呼召",
    "original": "人在外呼之招凶"
  },
  {
    "id": "zhougong-0259",
    "category": "帝王文武呼召",
    "original": "我欲共汝去大凶"
  },
  {
    "id": "zhougong-0260",
    "category": "帝王文武呼召",
    "original": "人云不用汝大吉"
  },
  {
    "id": "zhougong-0261",
    "category": "帝王文武呼召",
    "original": "與惡人言主口舌"
  },
  {
    "id": "zhougong-0262",
    "category": "帝王文武呼召",
    "original": "被殺害吉伏藏凶"
  },
  {
    "id": "zhougong-0263",
    "category": "帝王文武呼召",
    "original": "身生羽翼飛大吉"
  },
  {
    "id": "zhougong-0264",
    "category": "帝王文武呼召",
    "original": "身逃去得脫病去"
  },
  {
    "id": "zhougong-0265",
    "category": "帝王文武呼召",
    "original": "與人交易主有疾"
  },
  {
    "id": "zhougong-0266",
    "category": "帝王文武呼召",
    "original": "貧窮兵居主大吉"
  },
  {
    "id": "zhougong-0267",
    "category": "帝王文武呼召",
    "original": "合伴同行凶事至"
  },
  {
    "id": "zhougong-0268",
    "category": "帝王文武呼召",
    "original": "一切貴人皆吉祥"
  },
  {
    "id": "zhougong-0269",
    "category": "宮室屋宇倉庫",
    "original": "入帝王宮行大吉"
  },
  {
    "id": "zhougong-0270",
    "category": "宮室屋宇倉庫",
    "original": "拜朝廷者主富貴"
  },
  {
    "id": "zhougong-0271",
    "category": "宮室屋宇倉庫",
    "original": "入王侯府庫大吉"
  },
  {
    "id": "zhougong-0272",
    "category": "宮室屋宇倉庫",
    "original": "行道宮見仙主吉"
  },
  {
    "id": "zhougong-0273",
    "category": "宮室屋宇倉庫",
    "original": "坐官府中主大吉"
  },
  {
    "id": "zhougong-0274",
    "category": "宮室屋宇倉庫",
    "original": "神廟廣大事事吉"
  },
  {
    "id": "zhougong-0275",
    "category": "宮室屋宇倉庫",
    "original": "上樓閣壇主大吉"
  },
  {
    "id": "zhougong-0276",
    "category": "宮室屋宇倉庫",
    "original": "上高堂大富貴至"
  },
  {
    "id": "zhougong-0277",
    "category": "宮室屋宇倉庫",
    "original": "高樓飲酒富貴至"
  },
  {
    "id": "zhougong-0278",
    "category": "宮室屋宇倉庫",
    "original": "家起高樓安穩事"
  },
  {
    "id": "zhougong-0279",
    "category": "宮室屋宇倉庫",
    "original": "上城為人所拽吉"
  },
  {
    "id": "zhougong-0280",
    "category": "宮室屋宇倉庫",
    "original": "上城被執官職顯"
  },
  {
    "id": "zhougong-0281",
    "category": "宮室屋宇倉庫",
    "original": "城郭廣大財喜多"
  },
  {
    "id": "zhougong-0282",
    "category": "宮室屋宇倉庫",
    "original": "城中行凶出門吉"
  },
  {
    "id": "zhougong-0283",
    "category": "宮室屋宇倉庫",
    "original": "連城青色有喜吉"
  },
  {
    "id": "zhougong-0284",
    "category": "宮室屋宇倉庫",
    "original": "登赤城郭主大吉"
  },
  {
    "id": "zhougong-0285",
    "category": "宮室屋宇倉庫",
    "original": "蓋城上屋大吉利"
  },
  {
    "id": "zhougong-0286",
    "category": "宮室屋宇倉庫",
    "original": "上屋主富出園吉"
  },
  {
    "id": "zhougong-0287",
    "category": "宮室屋宇倉庫",
    "original": "上屋破壞家道凶"
  },
  {
    "id": "zhougong-0288",
    "category": "宮室屋宇倉庫",
    "original": "堂上有棺身安樂"
  },
  {
    "id": "zhougong-0289",
    "category": "宮室屋宇倉庫",
    "original": "正堂倒陷家主凶"
  },
  {
    "id": "zhougong-0290",
    "category": "宮室屋宇倉庫",
    "original": "覆蓋屋宇長命吉"
  },
  {
    "id": "zhougong-0291",
    "category": "宮室屋宇倉庫",
    "original": "屋宅更新主大吉"
  },
  {
    "id": "zhougong-0292",
    "category": "宮室屋宇倉庫",
    "original": "風吹屋動主遷移"
  },
  {
    "id": "zhougong-0293",
    "category": "宮室屋宇倉庫",
    "original": "遷入他人新宅吉"
  },
  {
    "id": "zhougong-0294",
    "category": "宮室屋宇倉庫",
    "original": "居出宅主妻喜事"
  },
  {
    "id": "zhougong-0295",
    "category": "宮室屋宇倉庫",
    "original": "搬移破屋主美妻"
  },
  {
    "id": "zhougong-0296",
    "category": "宮室屋宇倉庫",
    "original": "人或典房主官位"
  },
  {
    "id": "zhougong-0297",
    "category": "宮室屋宇倉庫",
    "original": "家道貧窮大吉利"
  },
  {
    "id": "zhougong-0298",
    "category": "宮室屋宇倉庫",
    "original": "洒掃宅舍遠人來"
  },
  {
    "id": "zhougong-0299",
    "category": "宮室屋宇倉庫",
    "original": "典賣典舍主失位"
  },
  {
    "id": "zhougong-0300",
    "category": "宮室屋宇倉庫",
    "original": "屋宅無人主死亡"
  },
  {
    "id": "zhougong-0301",
    "category": "宮室屋宇倉庫",
    "original": "屋上穿舟有暗昧"
  },
  {
    "id": "zhougong-0302",
    "category": "宮室屋宇倉庫",
    "original": "踰牆渡宅百事去"
  },
  {
    "id": "zhougong-0303",
    "category": "宮室屋宇倉庫",
    "original": "與人爭屋主大凶"
  },
  {
    "id": "zhougong-0304",
    "category": "宮室屋宇倉庫",
    "original": "與婦人爭屋主吉"
  },
  {
    "id": "zhougong-0305",
    "category": "宮室屋宇倉庫",
    "original": "房樑忽折主大凶"
  },
  {
    "id": "zhougong-0306",
    "category": "宮室屋宇倉庫",
    "original": "院宅坑下主死亡"
  },
  {
    "id": "zhougong-0307",
    "category": "宮室屋宇倉庫",
    "original": "妻男牆下官位至"
  },
  {
    "id": "zhougong-0308",
    "category": "宮室屋宇倉庫",
    "original": "牆上掘土主更政"
  },
  {
    "id": "zhougong-0309",
    "category": "宮室屋宇倉庫",
    "original": "軍人入宅主大吉"
  },
  {
    "id": "zhougong-0310",
    "category": "宮室屋宇倉庫",
    "original": "死央瓦落婦爭鬥"
  },
  {
    "id": "zhougong-0311",
    "category": "宮室屋宇倉庫",
    "original": "屋中生馬男信至"
  },
  {
    "id": "zhougong-0312",
    "category": "宮室屋宇倉庫",
    "original": "屋中生草家欲空"
  },
  {
    "id": "zhougong-0313",
    "category": "宮室屋宇倉庫",
    "original": "屋上生松柏益壽"
  },
  {
    "id": "zhougong-0314",
    "category": "宮室屋宇倉庫",
    "original": "修理田舍有大喜"
  },
  {
    "id": "zhougong-0315",
    "category": "宮室屋宇倉庫",
    "original": "入寺院中生男子"
  },
  {
    "id": "zhougong-0316",
    "category": "宮室屋宇倉庫",
    "original": "寺舍有經病人痊"
  },
  {
    "id": "zhougong-0317",
    "category": "宮室屋宇倉庫",
    "original": "遷移尼寺主病至"
  },
  {
    "id": "zhougong-0318",
    "category": "宮室屋宇倉庫",
    "original": "起蓋倉庫福祿至"
  },
  {
    "id": "zhougong-0319",
    "category": "宮室屋宇倉庫",
    "original": "入倉庫中大吉昂"
  },
  {
    "id": "zhougong-0320",
    "category": "宮室屋宇倉庫",
    "original": "倉庫崩壞百事凶"
  },
  {
    "id": "zhougong-0321",
    "category": "門戶井灶廚廁",
    "original": "門戶高大主富貴"
  },
  {
    "id": "zhougong-0322",
    "category": "門戶井灶廚廁",
    "original": "新開門戶大富貴"
  },
  {
    "id": "zhougong-0323",
    "category": "門戶井灶廚廁",
    "original": "門戶忽開主大吉"
  },
  {
    "id": "zhougong-0324",
    "category": "門戶井灶廚廁",
    "original": "門戶大開大吉利"
  },
  {
    "id": "zhougong-0325",
    "category": "門戶井灶廚廁",
    "original": "門更新主生貴子"
  },
  {
    "id": "zhougong-0326",
    "category": "門戶井灶廚廁",
    "original": "門自開妻有私情"
  },
  {
    "id": "zhougong-0327",
    "category": "門戶井灶廚廁",
    "original": "門戶裂開主大吉"
  },
  {
    "id": "zhougong-0328",
    "category": "門戶井灶廚廁",
    "original": "門戶破壞有凶事"
  },
  {
    "id": "zhougong-0329",
    "category": "門戶井灶廚廁",
    "original": "城門大開主口舌"
  },
  {
    "id": "zhougong-0330",
    "category": "門戶井灶廚廁",
    "original": "宮城塞者口舌至"
  },
  {
    "id": "zhougong-0331",
    "category": "門戶井灶廚廁",
    "original": "門戶閉塞事不通"
  },
  {
    "id": "zhougong-0332",
    "category": "門戶井灶廚廁",
    "original": "門戶破壞主大凶"
  },
  {
    "id": "zhougong-0333",
    "category": "門戶井灶廚廁",
    "original": "門扇自折奴僕走"
  },
  {
    "id": "zhougong-0334",
    "category": "門戶井灶廚廁",
    "original": "門戶內無人大凶"
  },
  {
    "id": "zhougong-0335",
    "category": "門戶井灶廚廁",
    "original": "修移門戶大吉利"
  },
  {
    "id": "zhougong-0336",
    "category": "門戶井灶廚廁",
    "original": "石為門戶主壽命"
  },
  {
    "id": "zhougong-0337",
    "category": "門戶井灶廚廁",
    "original": "門前生草作刺史"
  },
  {
    "id": "zhougong-0338",
    "category": "門戶井灶廚廁",
    "original": "門前坑溝事不成"
  },
  {
    "id": "zhougong-0339",
    "category": "門戶井灶廚廁",
    "original": "天火燒門主凶事"
  },
  {
    "id": "zhougong-0340",
    "category": "門戶井灶廚廁",
    "original": "屋開小門主私情"
  },
  {
    "id": "zhougong-0341",
    "category": "門戶井灶廚廁",
    "original": "穿井見水遠信至"
  },
  {
    "id": "zhougong-0342",
    "category": "門戶井灶廚廁",
    "original": "井自損壞家大敗"
  },
  {
    "id": "zhougong-0343",
    "category": "門戶井灶廚廁",
    "original": "井中沸溢主得財"
  },
  {
    "id": "zhougong-0344",
    "category": "門戶井灶廚廁",
    "original": "井枯涸者家財散"
  },
  {
    "id": "zhougong-0345",
    "category": "門戶井灶廚廁",
    "original": "井中照身祿位至"
  },
  {
    "id": "zhougong-0346",
    "category": "門戶井灶廚廁",
    "original": "身墜井中疾病凶"
  },
  {
    "id": "zhougong-0347",
    "category": "門戶井灶廚廁",
    "original": "房在井中主見病"
  },
  {
    "id": "zhougong-0348",
    "category": "門戶井灶廚廁",
    "original": "取井水清吉混凶"
  },
  {
    "id": "zhougong-0349",
    "category": "門戶井灶廚廁",
    "original": "井水負泥出財主"
  },
  {
    "id": "zhougong-0350",
    "category": "門戶井灶廚廁",
    "original": "井中欲乾家欲破"
  },
  {
    "id": "zhougong-0351",
    "category": "門戶井灶廚廁",
    "original": "井中有魚身主貴"
  },
  {
    "id": "zhougong-0352",
    "category": "門戶井灶廚廁",
    "original": "窺井有聲口舌生"
  },
  {
    "id": "zhougong-0353",
    "category": "門戶井灶廚廁",
    "original": "伏藏井中刑獄事"
  },
  {
    "id": "zhougong-0354",
    "category": "門戶井灶廚廁",
    "original": "醉落井中官事至"
  },
  {
    "id": "zhougong-0355",
    "category": "門戶井灶廚廁",
    "original": "家住井中長子凶"
  },
  {
    "id": "zhougong-0356",
    "category": "門戶井灶廚廁",
    "original": "人云出井喜氣至"
  },
  {
    "id": "zhougong-0357",
    "category": "門戶井灶廚廁",
    "original": "淘井造井主大貴"
  },
  {
    "id": "zhougong-0358",
    "category": "門戶井灶廚廁",
    "original": "器皿落井有吉事"
  },
  {
    "id": "zhougong-0359",
    "category": "門戶井灶廚廁",
    "original": "灶下水流得橫財"
  },
  {
    "id": "zhougong-0360",
    "category": "門戶井灶廚廁",
    "original": "灶下燃火有聲名"
  },
  {
    "id": "zhougong-0361",
    "category": "門戶井灶廚廁",
    "original": "灶釜破敗有死亡"
  },
  {
    "id": "zhougong-0362",
    "category": "門戶井灶廚廁",
    "original": "灶下吹者家破敗"
  },
  {
    "id": "zhougong-0363",
    "category": "門戶井灶廚廁",
    "original": "灶下鳴器主口舌"
  },
  {
    "id": "zhougong-0364",
    "category": "門戶井灶廚廁",
    "original": "屋有二灶事不成"
  },
  {
    "id": "zhougong-0365",
    "category": "門戶井灶廚廁",
    "original": "修造廚灶大吉利"
  },
  {
    "id": "zhougong-0366",
    "category": "門戶井灶廚廁",
    "original": "在官廚中得財祿"
  },
  {
    "id": "zhougong-0367",
    "category": "門戶井灶廚廁",
    "original": "自吹臼中妻妾亡"
  },
  {
    "id": "zhougong-0368",
    "category": "門戶井灶廚廁",
    "original": "淘廁者主得橫財"
  },
  {
    "id": "zhougong-0369",
    "category": "門戶井灶廚廁",
    "original": "上廁在屎尿中吉"
  },
  {
    "id": "zhougong-0370",
    "category": "門戶井灶廚廁",
    "original": "廁中屎溢大吉利"
  },
  {
    "id": "zhougong-0371",
    "category": "門戶井灶廚廁",
    "original": "糞中坐者主大凶"
  },
  {
    "id": "zhougong-0372",
    "category": "門戶井灶廚廁",
    "original": "糞土堆積主得財"
  },
  {
    "id": "zhougong-0373",
    "category": "金銀珠玉絹帛",
    "original": "金銀寶者主富貴"
  },
  {
    "id": "zhougong-0374",
    "category": "金銀珠玉絹帛",
    "original": "金銀珠玉大吉利"
  },
  {
    "id": "zhougong-0375",
    "category": "金銀珠玉絹帛",
    "original": "金銀杯皿有貴孕"
  },
  {
    "id": "zhougong-0376",
    "category": "金銀珠玉絹帛",
    "original": "金銀作鐺器大吉"
  },
  {
    "id": "zhougong-0377",
    "category": "金銀珠玉絹帛",
    "original": "玉積如山大富貴"
  },
  {
    "id": "zhougong-0378",
    "category": "金銀珠玉絹帛",
    "original": "得金玉環生貴子"
  },
  {
    "id": "zhougong-0379",
    "category": "金銀珠玉絹帛",
    "original": "銅鐺主有口舌至"
  },
  {
    "id": "zhougong-0380",
    "category": "金銀珠玉絹帛",
    "original": "珠玉滿懷主大凶"
  },
  {
    "id": "zhougong-0381",
    "category": "金銀珠玉絹帛",
    "original": "得玉碗器物皆吉"
  },
  {
    "id": "zhougong-0382",
    "category": "金銀珠玉絹帛",
    "original": "見鐵器物主得財"
  },
  {
    "id": "zhougong-0383",
    "category": "金銀珠玉絹帛",
    "original": "鉛與鍚者主得財"
  },
  {
    "id": "zhougong-0384",
    "category": "金銀珠玉絹帛",
    "original": "得銅物主大富貴"
  },
  {
    "id": "zhougong-0385",
    "category": "金銀珠玉絹帛",
    "original": "鑲嵌器物疾病去"
  },
  {
    "id": "zhougong-0386",
    "category": "金銀珠玉絹帛",
    "original": "還人錢物疾病去"
  },
  {
    "id": "zhougong-0387",
    "category": "金銀珠玉絹帛",
    "original": "拾得錢物皆大吉"
  },
  {
    "id": "zhougong-0388",
    "category": "金銀珠玉絹帛",
    "original": "錢春夏吉秋冬凶"
  },
  {
    "id": "zhougong-0389",
    "category": "金銀珠玉絹帛",
    "original": "家中分財主離敗"
  },
  {
    "id": "zhougong-0390",
    "category": "金銀珠玉絹帛",
    "original": "贈彩帛者主有權"
  },
  {
    "id": "zhougong-0391",
    "category": "金銀珠玉絹帛",
    "original": "貴人賜綾錦官至"
  },
  {
    "id": "zhougong-0392",
    "category": "金銀珠玉絹帛",
    "original": "人賜絹帛大吉昌"
  },
  {
    "id": "zhougong-0393",
    "category": "金銀珠玉絹帛",
    "original": "與人絲帛大凶惡"
  },
  {
    "id": "zhougong-0394",
    "category": "金銀珠玉絹帛",
    "original": "得他人麻布衣凶"
  },
  {
    "id": "zhougong-0395",
    "category": "金銀珠玉絹帛",
    "original": "得布帛遠親來至"
  },
  {
    "id": "zhougong-0396",
    "category": "金銀珠玉絹帛",
    "original": "與人衣服官事至"
  },
  {
    "id": "zhougong-0397",
    "category": "金銀珠玉絹帛",
    "original": "尋絲絹主進入口"
  },
  {
    "id": "zhougong-0398",
    "category": "金銀珠玉絹帛",
    "original": "紡績者主壽命長"
  },
  {
    "id": "zhougong-0399",
    "category": "金銀珠玉絹帛",
    "original": "經絡者主被人辱"
  },
  {
    "id": "zhougong-0400",
    "category": "金銀珠玉絹帛",
    "original": "箱器主口舌之事"
  },
  {
    "id": "zhougong-0401",
    "category": "鏡環釵釧梳篦",
    "original": "明鏡者吉暗者凶"
  },
  {
    "id": "zhougong-0402",
    "category": "鏡環釵釧梳篦",
    "original": "拾得鏡者招好妻"
  },
  {
    "id": "zhougong-0403",
    "category": "鏡環釵釧梳篦",
    "original": "將鏡自照遠信至"
  },
  {
    "id": "zhougong-0404",
    "category": "鏡環釵釧梳篦",
    "original": "鏡照他人妻妾凶"
  },
  {
    "id": "zhougong-0405",
    "category": "鏡環釵釧梳篦",
    "original": "得他人鏡有貴子"
  },
  {
    "id": "zhougong-0406",
    "category": "鏡環釵釧梳篦",
    "original": "他人弄己鏡妻凶"
  },
  {
    "id": "zhougong-0407",
    "category": "鏡環釵釧梳篦",
    "original": "鏡破主夫妻離別"
  },
  {
    "id": "zhougong-0408",
    "category": "鏡環釵釧梳篦",
    "original": "金釵動有遠行事"
  },
  {
    "id": "zhougong-0409",
    "category": "鏡環釵釧梳篦",
    "original": "金鈿成雙增愛妾"
  },
  {
    "id": "zhougong-0410",
    "category": "鏡環釵釧梳篦",
    "original": "釵釧相敲妻別凶"
  },
  {
    "id": "zhougong-0411",
    "category": "鏡環釵釧梳篦",
    "original": "金釵耀主生貴子"
  },
  {
    "id": "zhougong-0412",
    "category": "鏡環釵釧梳篦",
    "original": "花釵妻妾有姦佞"
  },
  {
    "id": "zhougong-0413",
    "category": "鏡環釵釧梳篦",
    "original": "銀釧夫妻主相毆"
  },
  {
    "id": "zhougong-0414",
    "category": "鏡環釵釧梳篦",
    "original": "花壓妻妾生外心"
  },
  {
    "id": "zhougong-0415",
    "category": "鏡環釵釧梳篦",
    "original": "人與梳篦得美妾"
  },
  {
    "id": "zhougong-0416",
    "category": "鏡環釵釧梳篦",
    "original": "牙木梳舊事盡去"
  },
  {
    "id": "zhougong-0417",
    "category": "鏡環釵釧梳篦",
    "original": "見篦子貴人提攜"
  },
  {
    "id": "zhougong-0418",
    "category": "鏡環釵釧梳篦",
    "original": "得篦子者美女至"
  },
  {
    "id": "zhougong-0419",
    "category": "鏡環釵釧梳篦",
    "original": "刷牙者病患不生"
  },
  {
    "id": "zhougong-0420",
    "category": "鏡環釵釧梳篦",
    "original": "得胭脂粉主生女"
  },
  {
    "id": "zhougong-0421",
    "category": "鏡環釵釧梳篦",
    "original": "見脂粉主大財利"
  },
  {
    "id": "zhougong-0422",
    "category": "鏡環釵釧梳篦",
    "original": "得粉僕妻生嬌女"
  },
  {
    "id": "zhougong-0423",
    "category": "鏡環釵釧梳篦",
    "original": "手帕者主口舌事"
  },
  {
    "id": "zhougong-0424",
    "category": "鏡環釵釧梳篦",
    "original": "針線得者百事就"
  },
  {
    "id": "zhougong-0425",
    "category": "衣帳毯褥匙櫡",
    "original": "床帳改主官遷移"
  },
  {
    "id": "zhougong-0426",
    "category": "衣帳毯褥匙櫡",
    "original": "舒展床帳大富貴"
  },
  {
    "id": "zhougong-0427",
    "category": "衣帳毯褥匙櫡",
    "original": "新安床帳遠人來"
  },
  {
    "id": "zhougong-0428",
    "category": "衣帳毯褥匙櫡",
    "original": "床帳出門者妻亡"
  },
  {
    "id": "zhougong-0429",
    "category": "衣帳毯褥匙櫡",
    "original": "床帳收換移居吉"
  },
  {
    "id": "zhougong-0430",
    "category": "衣帳毯褥匙櫡",
    "original": "床上有蟻至不祥"
  },
  {
    "id": "zhougong-0431",
    "category": "衣帳毯褥匙櫡",
    "original": "床帳破損妻欲亡"
  },
  {
    "id": "zhougong-0432",
    "category": "衣帳毯褥匙櫡",
    "original": "開帳幔主有酒食"
  },
  {
    "id": "zhougong-0433",
    "category": "衣帳毯褥匙櫡",
    "original": "帳幔壞者妻子病"
  },
  {
    "id": "zhougong-0434",
    "category": "衣帳毯褥匙櫡",
    "original": "床腳新換奴僕凶"
  },
  {
    "id": "zhougong-0435",
    "category": "衣帳毯褥匙櫡",
    "original": "上床臥者大凶惡"
  },
  {
    "id": "zhougong-0436",
    "category": "衣帳毯褥匙櫡",
    "original": "血在床妻妾有姦"
  },
  {
    "id": "zhougong-0437",
    "category": "衣帳毯褥匙櫡",
    "original": "洗床帳則主大吉"
  },
  {
    "id": "zhougong-0438",
    "category": "衣帳毯褥匙櫡",
    "original": "薦蓆入吉出則凶"
  },
  {
    "id": "zhougong-0439",
    "category": "衣帳毯褥匙櫡",
    "original": "破蓆者主失官位"
  },
  {
    "id": "zhougong-0440",
    "category": "衣帳毯褥匙櫡",
    "original": "換蓆入吉出則凶"
  },
  {
    "id": "zhougong-0441",
    "category": "衣帳毯褥匙櫡",
    "original": "蓆簞者主有力助"
  },
  {
    "id": "zhougong-0442",
    "category": "衣帳毯褥匙櫡",
    "original": "毯褥舖陳萬事穩"
  },
  {
    "id": "zhougong-0443",
    "category": "衣帳毯褥匙櫡",
    "original": "毀蓆幔者妻有姦"
  },
  {
    "id": "zhougong-0444",
    "category": "衣帳毯褥匙櫡",
    "original": "新簾者主得好妻"
  },
  {
    "id": "zhougong-0445",
    "category": "衣帳毯褥匙櫡",
    "original": "舖蓆合坐得官位"
  },
  {
    "id": "zhougong-0446",
    "category": "衣帳毯褥匙櫡",
    "original": "好被自蓋主大吉"
  },
  {
    "id": "zhougong-0447",
    "category": "衣帳毯褥匙櫡",
    "original": "見好枕有貴人扶"
  },
  {
    "id": "zhougong-0448",
    "category": "衣帳毯褥匙櫡",
    "original": "見手帕主有口舌"
  },
  {
    "id": "zhougong-0449",
    "category": "衣帳毯褥匙櫡",
    "original": "手中縛布病患至"
  },
  {
    "id": "zhougong-0450",
    "category": "衣帳毯褥匙櫡",
    "original": "毛肩忽持官事至"
  },
  {
    "id": "zhougong-0451",
    "category": "衣帳毯褥匙櫡",
    "original": "鼎鼐者主得大財"
  },
  {
    "id": "zhougong-0452",
    "category": "衣帳毯褥匙櫡",
    "original": "釜溢者主得大財"
  },
  {
    "id": "zhougong-0453",
    "category": "衣帳毯褥匙櫡",
    "original": "玉石器主有人助"
  },
  {
    "id": "zhougong-0454",
    "category": "衣帳毯褥匙櫡",
    "original": "銅鐺者主口舌至"
  },
  {
    "id": "zhougong-0455",
    "category": "衣帳毯褥匙櫡",
    "original": "鍋鐵破主喪事來"
  },
  {
    "id": "zhougong-0456",
    "category": "衣帳毯褥匙櫡",
    "original": "鐺盞破主有惡事"
  },
  {
    "id": "zhougong-0457",
    "category": "衣帳毯褥匙櫡",
    "original": "磁碗者主酒食至"
  },
  {
    "id": "zhougong-0458",
    "category": "衣帳毯褥匙櫡",
    "original": "磁碟者主口舌至"
  },
  {
    "id": "zhougong-0459",
    "category": "衣帳毯褥匙櫡",
    "original": "匙主益妻妾子孫"
  },
  {
    "id": "zhougong-0460",
    "category": "衣帳毯褥匙櫡",
    "original": "櫡主益田宅奴僕"
  },
  {
    "id": "zhougong-0461",
    "category": "衣帳毯褥匙櫡",
    "original": "盆主益倉庫大吉"
  },
  {
    "id": "zhougong-0462",
    "category": "衣帳毯褥匙櫡",
    "original": "棳盆脫底主財散"
  },
  {
    "id": "zhougong-0463",
    "category": "衣帳毯褥匙櫡",
    "original": "入盆甕器大富貴"
  },
  {
    "id": "zhougong-0464",
    "category": "衣帳毯褥匙櫡",
    "original": "洗面盆者美妾至"
  },
  {
    "id": "zhougong-0465",
    "category": "衣帳毯褥匙櫡",
    "original": "大小盆者主團圓"
  },
  {
    "id": "zhougong-0466",
    "category": "衣帳毯褥匙櫡",
    "original": "得盆子者所求得"
  },
  {
    "id": "zhougong-0467",
    "category": "衣帳毯褥匙櫡",
    "original": "桶盛水者主大吉"
  },
  {
    "id": "zhougong-0468",
    "category": "衣帳毯褥匙櫡",
    "original": "桶無水者主大凶"
  },
  {
    "id": "zhougong-0469",
    "category": "衣帳毯褥匙櫡",
    "original": "人送大桶主得利"
  },
  {
    "id": "zhougong-0470",
    "category": "衣帳毯褥匙櫡",
    "original": "桌架於宅事不成"
  },
  {
    "id": "zhougong-0471",
    "category": "衣帳毯褥匙櫡",
    "original": "鋸主有斷決之事"
  },
  {
    "id": "zhougong-0472",
    "category": "衣帳毯褥匙櫡",
    "original": "碾衣食移居大吉"
  },
  {
    "id": "zhougong-0473",
    "category": "衣帳毯褥匙櫡",
    "original": "鎚鑽者主侵害事"
  },
  {
    "id": "zhougong-0474",
    "category": "衣帳毯褥匙櫡",
    "original": "鎚欲舉動有人持"
  },
  {
    "id": "zhougong-0475",
    "category": "衣帳毯褥匙櫡",
    "original": "鑿主被人驅使吉"
  },
  {
    "id": "zhougong-0476",
    "category": "衣帳毯褥匙櫡",
    "original": "熨斗盛火好事成"
  },
  {
    "id": "zhougong-0477",
    "category": "衣帳毯褥匙櫡",
    "original": "燻籠者益增田產"
  },
  {
    "id": "zhougong-0478",
    "category": "衣帳毯褥匙櫡",
    "original": "人與秤者主權位"
  },
  {
    "id": "zhougong-0479",
    "category": "衣帳毯褥匙櫡",
    "original": "繩索主長命大吉"
  },
  {
    "id": "zhougong-0480",
    "category": "衣帳毯褥匙櫡",
    "original": "繩索斷者主凶惡"
  },
  {
    "id": "zhougong-0481",
    "category": "衣帳毯褥匙櫡",
    "original": "人與鑿者得失金"
  },
  {
    "id": "zhougong-0482",
    "category": "衣帳毯褥匙櫡",
    "original": "人送帶者主得位"
  },
  {
    "id": "zhougong-0483",
    "category": "船車遊行物件",
    "original": "船飛行主大富貴"
  },
  {
    "id": "zhougong-0484",
    "category": "船車遊行物件",
    "original": "船淺在岸是非厄"
  },
  {
    "id": "zhougong-0485",
    "category": "船車遊行物件",
    "original": "乘船渡江河得官"
  },
  {
    "id": "zhougong-0486",
    "category": "船車遊行物件",
    "original": "船中有水主得財"
  },
  {
    "id": "zhougong-0487",
    "category": "船車遊行物件",
    "original": "乘船看日月得職"
  },
  {
    "id": "zhougong-0488",
    "category": "船車遊行物件",
    "original": "乘船過日月主富"
  },
  {
    "id": "zhougong-0489",
    "category": "船車遊行物件",
    "original": "乘船飲酒遠客至"
  },
  {
    "id": "zhougong-0490",
    "category": "船車遊行物件",
    "original": "與人同船主移居"
  },
  {
    "id": "zhougong-0491",
    "category": "船車遊行物件",
    "original": "乘船風帆大吉利"
  },
  {
    "id": "zhougong-0492",
    "category": "船車遊行物件",
    "original": "乘船見舵主安穩"
  },
  {
    "id": "zhougong-0493",
    "category": "船車遊行物件",
    "original": "乘船橋下過大吉"
  },
  {
    "id": "zhougong-0494",
    "category": "船車遊行物件",
    "original": "病人乘船必主死"
  },
  {
    "id": "zhougong-0495",
    "category": "船車遊行物件",
    "original": "助父乘船官位至"
  },
  {
    "id": "zhougong-0496",
    "category": "船車遊行物件",
    "original": "身臥船中主有凶"
  },
  {
    "id": "zhougong-0497",
    "category": "船車遊行物件",
    "original": "執火入船主大吉"
  },
  {
    "id": "zhougong-0498",
    "category": "船車遊行物件",
    "original": "家中乘船主沒財"
  },
  {
    "id": "zhougong-0499",
    "category": "船車遊行物件",
    "original": "乘船看花酒食至"
  },
  {
    "id": "zhougong-0500",
    "category": "船車遊行物件",
    "original": "船車破碎主不祥"
  },
  {
    "id": "zhougong-0501",
    "category": "船車遊行物件",
    "original": "車輪破夫妻相別"
  },
  {
    "id": "zhougong-0502",
    "category": "船車遊行物件",
    "original": "車輪折倒主破敗"
  },
  {
    "id": "zhougong-0503",
    "category": "船車遊行物件",
    "original": "車載不起厄事去"
  },
  {
    "id": "zhougong-0504",
    "category": "船車遊行物件",
    "original": "駕車遊行祿位至"
  },
  {
    "id": "zhougong-0505",
    "category": "船車遊行物件",
    "original": "車行主百事順和"
  },
  {
    "id": "zhougong-0506",
    "category": "船車遊行物件",
    "original": "車不行所求不遂"
  },
  {
    "id": "zhougong-0507",
    "category": "船車遊行物件",
    "original": "車入門主有凶事"
  },
  {
    "id": "zhougong-0508",
    "category": "船車遊行物件",
    "original": "病人上車主大凶"
  },
  {
    "id": "zhougong-0509",
    "category": "船車遊行物件",
    "original": "喪車遇者主災散"
  },
  {
    "id": "zhougong-0510",
    "category": "船車遊行物件",
    "original": "行車白馬主大吉"
  },
  {
    "id": "zhougong-0511",
    "category": "船車遊行物件",
    "original": "四馬駕車吉反凶"
  },
  {
    "id": "zhougong-0512",
    "category": "船車遊行物件",
    "original": "以羊駕車事不常"
  },
  {
    "id": "zhougong-0513",
    "category": "船車遊行物件",
    "original": "備馬者主遠行事"
  },
  {
    "id": "zhougong-0514",
    "category": "船車遊行物件",
    "original": "遠行出入命通達"
  },
  {
    "id": "zhougong-0515",
    "category": "道路橋梁市集",
    "original": "見四路通名利遂"
  },
  {
    "id": "zhougong-0516",
    "category": "道路橋梁市集",
    "original": "道中得財主通達"
  },
  {
    "id": "zhougong-0517",
    "category": "道路橋梁市集",
    "original": "道泥荊棘事不成"
  },
  {
    "id": "zhougong-0518",
    "category": "道路橋梁市集",
    "original": "大道崩陷主失財"
  },
  {
    "id": "zhougong-0519",
    "category": "道路橋梁市集",
    "original": "修橋樑者萬事和"
  },
  {
    "id": "zhougong-0520",
    "category": "道路橋梁市集",
    "original": "見渡橋主有官事"
  },
  {
    "id": "zhougong-0521",
    "category": "道路橋梁市集",
    "original": "橋上坐主祿位至"
  },
  {
    "id": "zhougong-0522",
    "category": "道路橋梁市集",
    "original": "見橋壞主有官事"
  },
  {
    "id": "zhougong-0523",
    "category": "道路橋梁市集",
    "original": "攜手上橋妻有孕"
  },
  {
    "id": "zhougong-0524",
    "category": "道路橋梁市集",
    "original": "橋上呼喚訟得理"
  },
  {
    "id": "zhougong-0525",
    "category": "道路橋梁市集",
    "original": "新造橋者大和合"
  },
  {
    "id": "zhougong-0526",
    "category": "道路橋梁市集",
    "original": "橋斷者主有口舌"
  },
  {
    "id": "zhougong-0527",
    "category": "道路橋梁市集",
    "original": "橋柱折者子孫凶"
  },
  {
    "id": "zhougong-0528",
    "category": "道路橋梁市集",
    "original": "橋路上往車皆凶"
  },
  {
    "id": "zhougong-0529",
    "category": "道路橋梁市集",
    "original": "夫妻入市主置產"
  },
  {
    "id": "zhougong-0530",
    "category": "道路橋梁市集",
    "original": "見市中無人主凶"
  },
  {
    "id": "zhougong-0531",
    "category": "夫妻產孕交懽",
    "original": "夫妻宴會主相別"
  },
  {
    "id": "zhougong-0532",
    "category": "夫妻產孕交懽",
    "original": "夫妻相罵主病患"
  },
  {
    "id": "zhougong-0533",
    "category": "夫妻產孕交懽",
    "original": "夫妻分釵主離別"
  },
  {
    "id": "zhougong-0534",
    "category": "夫妻產孕交懽",
    "original": "夫妻相打欲和會"
  },
  {
    "id": "zhougong-0535",
    "category": "夫妻產孕交懽",
    "original": "同婦人行主失財"
  },
  {
    "id": "zhougong-0536",
    "category": "夫妻產孕交懽",
    "original": "抱婦人主有喜事"
  },
  {
    "id": "zhougong-0537",
    "category": "夫妻產孕交懽",
    "original": "與婦人交有邪祟"
  },
  {
    "id": "zhougong-0538",
    "category": "夫妻產孕交懽",
    "original": "與婦人共坐大吉"
  },
  {
    "id": "zhougong-0539",
    "category": "夫妻產孕交懽",
    "original": "抱夫主大得財喜"
  },
  {
    "id": "zhougong-0540",
    "category": "夫妻產孕交懽",
    "original": "婦人與夫入水吉"
  },
  {
    "id": "zhougong-0541",
    "category": "夫妻產孕交懽",
    "original": "夫妻各與梳頭吉"
  },
  {
    "id": "zhougong-0542",
    "category": "夫妻產孕交懽",
    "original": "夫妻相拜主分散"
  },
  {
    "id": "zhougong-0543",
    "category": "夫妻產孕交懽",
    "original": "交接男子主失財"
  },
  {
    "id": "zhougong-0544",
    "category": "夫妻產孕交懽",
    "original": "妻著錦衣生貴子"
  },
  {
    "id": "zhougong-0545",
    "category": "夫妻產孕交懽",
    "original": "妻有孕主外私情"
  },
  {
    "id": "zhougong-0546",
    "category": "夫妻產孕交懽",
    "original": "見婦人陰主口舌"
  },
  {
    "id": "zhougong-0547",
    "category": "夫妻產孕交懽",
    "original": "婦人赤身主大吉"
  },
  {
    "id": "zhougong-0548",
    "category": "夫妻產孕交懽",
    "original": "男子裸體命通達"
  },
  {
    "id": "zhougong-0549",
    "category": "夫妻產孕交懽",
    "original": "兄弟分別口舌臨"
  },
  {
    "id": "zhougong-0550",
    "category": "夫妻產孕交懽",
    "original": "抱小兒女主口舌"
  },
  {
    "id": "zhougong-0551",
    "category": "夫妻產孕交懽",
    "original": "小兒死者主口舌"
  },
  {
    "id": "zhougong-0552",
    "category": "夫妻產孕交懽",
    "original": "新生男女主大吉"
  },
  {
    "id": "zhougong-0553",
    "category": "夫妻產孕交懽",
    "original": "見嫁娶及孝主凶"
  },
  {
    "id": "zhougong-0554",
    "category": "夫妻產孕交懽",
    "original": "男子化為尼姑凶"
  },
  {
    "id": "zhougong-0555",
    "category": "飲食酒肉瓜菜",
    "original": "人請飲酒主長命"
  },
  {
    "id": "zhougong-0556",
    "category": "飲食酒肉瓜菜",
    "original": "與人飲酒有口舌"
  },
  {
    "id": "zhougong-0557",
    "category": "飲食酒肉瓜菜",
    "original": "與人吃會富貴至"
  },
  {
    "id": "zhougong-0558",
    "category": "飲食酒肉瓜菜",
    "original": "筵會客人家欲破"
  },
  {
    "id": "zhougong-0559",
    "category": "飲食酒肉瓜菜",
    "original": "飲酒者主哭泣事"
  },
  {
    "id": "zhougong-0560",
    "category": "飲食酒肉瓜菜",
    "original": "飲酒至醉主疾病"
  },
  {
    "id": "zhougong-0561",
    "category": "飲食酒肉瓜菜",
    "original": "貴人賜宴主疾病"
  },
  {
    "id": "zhougong-0562",
    "category": "飲食酒肉瓜菜",
    "original": "與貴人對飲大吉"
  },
  {
    "id": "zhougong-0563",
    "category": "飲食酒肉瓜菜",
    "original": "人請吃酥酪主喜"
  },
  {
    "id": "zhougong-0564",
    "category": "飲食酒肉瓜菜",
    "original": "與人吃乳尊親至"
  },
  {
    "id": "zhougong-0565",
    "category": "飲食酒肉瓜菜",
    "original": "與人吃蜜大吉利"
  },
  {
    "id": "zhougong-0566",
    "category": "飲食酒肉瓜菜",
    "original": "嘔吐者病人主瘥"
  },
  {
    "id": "zhougong-0567",
    "category": "飲食酒肉瓜菜",
    "original": "食水者主得大利"
  },
  {
    "id": "zhougong-0568",
    "category": "飲食酒肉瓜菜",
    "original": "死人食者主疾病"
  },
  {
    "id": "zhougong-0569",
    "category": "飲食酒肉瓜菜",
    "original": "食牛肉於堂上吉"
  },
  {
    "id": "zhougong-0570",
    "category": "飲食酒肉瓜菜",
    "original": "食犬肉主有爭訟"
  },
  {
    "id": "zhougong-0571",
    "category": "飲食酒肉瓜菜",
    "original": "食豬肉主疾病至"
  },
  {
    "id": "zhougong-0572",
    "category": "飲食酒肉瓜菜",
    "original": "刀割豬肉主生病"
  },
  {
    "id": "zhougong-0573",
    "category": "飲食酒肉瓜菜",
    "original": "食生肉凶熟肉吉"
  },
  {
    "id": "zhougong-0574",
    "category": "飲食酒肉瓜菜",
    "original": "食自死肉主別離"
  },
  {
    "id": "zhougong-0575",
    "category": "飲食酒肉瓜菜",
    "original": "食鵝肉主妾疾病"
  },
  {
    "id": "zhougong-0576",
    "category": "飲食酒肉瓜菜",
    "original": "食雞鴨等肉皆吉"
  },
  {
    "id": "zhougong-0577",
    "category": "飲食酒肉瓜菜",
    "original": "食饅頭主口舌散"
  },
  {
    "id": "zhougong-0578",
    "category": "飲食酒肉瓜菜",
    "original": "見饅頭未食主氣"
  },
  {
    "id": "zhougong-0579",
    "category": "飲食酒肉瓜菜",
    "original": "食爛瓜主生疾病"
  },
  {
    "id": "zhougong-0580",
    "category": "飲食酒肉瓜菜",
    "original": "食餅食飯心不遂"
  },
  {
    "id": "zhougong-0581",
    "category": "飲食酒肉瓜菜",
    "original": "食瓜子主生貴子"
  },
  {
    "id": "zhougong-0582",
    "category": "飲食酒肉瓜菜",
    "original": "食柿食柑主疾病"
  },
  {
    "id": "zhougong-0583",
    "category": "飲食酒肉瓜菜",
    "original": "食柿桃離而復合"
  },
  {
    "id": "zhougong-0584",
    "category": "飲食酒肉瓜菜",
    "original": "食棗者主生貴子"
  },
  {
    "id": "zhougong-0585",
    "category": "飲食酒肉瓜菜",
    "original": "食桑椹主生貴子"
  },
  {
    "id": "zhougong-0586",
    "category": "飲食酒肉瓜菜",
    "original": "食粟者主有分離"
  },
  {
    "id": "zhougong-0587",
    "category": "飲食酒肉瓜菜",
    "original": "食梨者主失財帛"
  },
  {
    "id": "zhougong-0588",
    "category": "飲食酒肉瓜菜",
    "original": "食一切菜者凶至"
  },
  {
    "id": "zhougong-0589",
    "category": "飲食酒肉瓜菜",
    "original": "食茄者主妻有子"
  },
  {
    "id": "zhougong-0590",
    "category": "飲食酒肉瓜菜",
    "original": "食蔥韭主有爭鬥"
  },
  {
    "id": "zhougong-0591",
    "category": "飲食酒肉瓜菜",
    "original": "食薤者有重傷至"
  },
  {
    "id": "zhougong-0592",
    "category": "飲食酒肉瓜菜",
    "original": "食蒜者主災害至"
  },
  {
    "id": "zhougong-0593",
    "category": "飲食酒肉瓜菜",
    "original": "食菜見菜黃主凶"
  },
  {
    "id": "zhougong-0594",
    "category": "飲食酒肉瓜菜",
    "original": "食油鹽醬酸豉吉"
  },
  {
    "id": "zhougong-0595",
    "category": "塚墓棺槨迎送",
    "original": "塚墓高者大吉利"
  },
  {
    "id": "zhougong-0596",
    "category": "塚墓棺槨迎送",
    "original": "新塚棺槨主憂除"
  },
  {
    "id": "zhougong-0597",
    "category": "塚墓棺槨迎送",
    "original": "塚墓上有雲氣吉"
  },
  {
    "id": "zhougong-0598",
    "category": "塚墓棺槨迎送",
    "original": "塚墓門開百事吉"
  },
  {
    "id": "zhougong-0599",
    "category": "塚墓棺槨迎送",
    "original": "塚墓上明吉暗凶"
  },
  {
    "id": "zhougong-0600",
    "category": "塚墓棺槨迎送",
    "original": "塚墓生樹吉折凶"
  },
  {
    "id": "zhougong-0601",
    "category": "塚墓棺槨迎送",
    "original": "塚墓上開花大吉"
  },
  {
    "id": "zhougong-0602",
    "category": "塚墓棺槨迎送",
    "original": "棺自出墓中大吉"
  },
  {
    "id": "zhougong-0603",
    "category": "塚墓棺槨迎送",
    "original": "抬棺入宅祿位至"
  },
  {
    "id": "zhougong-0604",
    "category": "塚墓棺槨迎送",
    "original": "死人出棺外客至"
  },
  {
    "id": "zhougong-0605",
    "category": "塚墓棺槨迎送",
    "original": "開棺與死人言凶"
  },
  {
    "id": "zhougong-0606",
    "category": "塚墓棺槨迎送",
    "original": "棺殮死人主得財"
  },
  {
    "id": "zhougong-0607",
    "category": "塚墓棺槨迎送",
    "original": "見棺水上大得財"
  },
  {
    "id": "zhougong-0608",
    "category": "塚墓棺槨迎送",
    "original": "空遠無人主遠行"
  },
  {
    "id": "zhougong-0609",
    "category": "文書筆硯兵器",
    "original": "各色經書大富貴"
  },
  {
    "id": "zhougong-0610",
    "category": "文書筆硯兵器",
    "original": "五色紙者大益財"
  },
  {
    "id": "zhougong-0611",
    "category": "文書筆硯兵器",
    "original": "吞五色紙詩書進"
  },
  {
    "id": "zhougong-0612",
    "category": "文書筆硯兵器",
    "original": "几上有書祿位至"
  },
  {
    "id": "zhougong-0613",
    "category": "文書筆硯兵器",
    "original": "詩文書寫字大吉"
  },
  {
    "id": "zhougong-0614",
    "category": "文書筆硯兵器",
    "original": "有人教書大富貴"
  },
  {
    "id": "zhougong-0615",
    "category": "文書筆硯兵器",
    "original": "見讀書者主聰明"
  },
  {
    "id": "zhougong-0616",
    "category": "文書筆硯兵器",
    "original": "觀人讀書生貴子"
  },
  {
    "id": "zhougong-0617",
    "category": "文書筆硯兵器",
    "original": "得曆日者中黃甲"
  },
  {
    "id": "zhougong-0618",
    "category": "文書筆硯兵器",
    "original": "封書信者主通達"
  },
  {
    "id": "zhougong-0619",
    "category": "文書筆硯兵器",
    "original": "手弄筆硯主遠信"
  },
  {
    "id": "zhougong-0620",
    "category": "文書筆硯兵器",
    "original": "人與墨者文章進"
  },
  {
    "id": "zhougong-0621",
    "category": "文書筆硯兵器",
    "original": "人將己筆文章退"
  },
  {
    "id": "zhougong-0622",
    "category": "文書筆硯兵器",
    "original": "他人送筆主才進"
  },
  {
    "id": "zhougong-0623",
    "category": "文書筆硯兵器",
    "original": "君王隊伍有異名"
  },
  {
    "id": "zhougong-0624",
    "category": "文書筆硯兵器",
    "original": "得大赦者宅舍凶"
  },
  {
    "id": "zhougong-0625",
    "category": "文書筆硯兵器",
    "original": "就人卜易主疾病"
  },
  {
    "id": "zhougong-0626",
    "category": "文書筆硯兵器",
    "original": "受人紙錢主大吉"
  },
  {
    "id": "zhougong-0627",
    "category": "文書筆硯兵器",
    "original": "公座移動主遷官"
  },
  {
    "id": "zhougong-0628",
    "category": "文書筆硯兵器",
    "original": "受職上官財物來"
  },
  {
    "id": "zhougong-0629",
    "category": "文書筆硯兵器",
    "original": "佩印公爵主大吉"
  },
  {
    "id": "zhougong-0630",
    "category": "文書筆硯兵器",
    "original": "佩印執節主移居"
  },
  {
    "id": "zhougong-0631",
    "category": "文書筆硯兵器",
    "original": "佩印信者名譽出"
  },
  {
    "id": "zhougong-0632",
    "category": "文書筆硯兵器",
    "original": "緩印改遷生貴子"
  },
  {
    "id": "zhougong-0633",
    "category": "文書筆硯兵器",
    "original": "碁子主添丁進口"
  },
  {
    "id": "zhougong-0634",
    "category": "文書筆硯兵器",
    "original": "打球者主得虛名"
  },
  {
    "id": "zhougong-0635",
    "category": "文書筆硯兵器",
    "original": "兵馬入城福祿至"
  },
  {
    "id": "zhougong-0636",
    "category": "文書筆硯兵器",
    "original": "率眾破賊所求得"
  },
  {
    "id": "zhougong-0637",
    "category": "文書筆硯兵器",
    "original": "在軍陣中主大吉"
  },
  {
    "id": "zhougong-0638",
    "category": "文書筆硯兵器",
    "original": "將卒隨行主喜事"
  },
  {
    "id": "zhougong-0639",
    "category": "文書筆硯兵器",
    "original": "征人初出事未成"
  },
  {
    "id": "zhougong-0640",
    "category": "文書筆硯兵器",
    "original": "征人回者主疾病"
  },
  {
    "id": "zhougong-0641",
    "category": "文書筆硯兵器",
    "original": "見軍兵敗主凶事"
  },
  {
    "id": "zhougong-0642",
    "category": "文書筆硯兵器",
    "original": "己射人必主遠行"
  },
  {
    "id": "zhougong-0643",
    "category": "文書筆硯兵器",
    "original": "人射己有行人至"
  },
  {
    "id": "zhougong-0644",
    "category": "文書筆硯兵器",
    "original": "持弓矢者主大吉"
  },
  {
    "id": "zhougong-0645",
    "category": "文書筆硯兵器",
    "original": "挽弓斷弦主凶惡"
  },
  {
    "id": "zhougong-0646",
    "category": "文書筆硯兵器",
    "original": "人送弓弩得人力"
  },
  {
    "id": "zhougong-0647",
    "category": "文書筆硯兵器",
    "original": "弩弦難上兄弟散"
  },
  {
    "id": "zhougong-0648",
    "category": "文書筆硯兵器",
    "original": "弓弩相鬥主爭論"
  },
  {
    "id": "zhougong-0649",
    "category": "文書筆硯兵器",
    "original": "戈鉞有光祿位至"
  },
  {
    "id": "zhougong-0650",
    "category": "文書筆硯兵器",
    "original": "披甲仗劍得高官"
  },
  {
    "id": "zhougong-0651",
    "category": "哀樂病死歌唱",
    "original": "與人哭泣有慶賀"
  },
  {
    "id": "zhougong-0652",
    "category": "哀樂病死歌唱",
    "original": "放聲大哭歡樂至"
  },
  {
    "id": "zhougong-0653",
    "category": "哀樂病死歌唱",
    "original": "身著孝服官祿至"
  },
  {
    "id": "zhougong-0654",
    "category": "哀樂病死歌唱",
    "original": "遠人來悲泣主凶"
  },
  {
    "id": "zhougong-0655",
    "category": "哀樂病死歌唱",
    "original": "床上哭泣主大凶"
  },
  {
    "id": "zhougong-0656",
    "category": "哀樂病死歌唱",
    "original": "見歌舞者口舌至"
  },
  {
    "id": "zhougong-0657",
    "category": "哀樂病死歌唱",
    "original": "家中歡喜百事吉"
  },
  {
    "id": "zhougong-0658",
    "category": "哀樂病死歌唱",
    "original": "懷中琵琶得人助"
  },
  {
    "id": "zhougong-0659",
    "category": "哀樂病死歌唱",
    "original": "他人與笛有名聲"
  },
  {
    "id": "zhougong-0660",
    "category": "哀樂病死歌唱",
    "original": "與人拍板有口舌"
  },
  {
    "id": "zhougong-0661",
    "category": "哀樂病死歌唱",
    "original": "堂上歌樂主喪事"
  },
  {
    "id": "zhougong-0662",
    "category": "哀樂病死歌唱",
    "original": "吹笙者主有更改"
  },
  {
    "id": "zhougong-0663",
    "category": "哀樂病死歌唱",
    "original": "吹笛打鼓有吉慶"
  },
  {
    "id": "zhougong-0664",
    "category": "哀樂病死歌唱",
    "original": "他人作樂訟有理"
  },
  {
    "id": "zhougong-0665",
    "category": "哀樂病死歌唱",
    "original": "露齒哭者有爭訟"
  },
  {
    "id": "zhougong-0666",
    "category": "哀樂病死歌唱",
    "original": "病臥為人扶加官"
  },
  {
    "id": "zhougong-0667",
    "category": "哀樂病死歌唱",
    "original": "病重者主有凶事"
  },
  {
    "id": "zhougong-0668",
    "category": "哀樂病死歌唱",
    "original": "自疾病者主有喜"
  },
  {
    "id": "zhougong-0669",
    "category": "哀樂病死歌唱",
    "original": "病人歌唱主大凶"
  },
  {
    "id": "zhougong-0670",
    "category": "哀樂病死歌唱",
    "original": "病人哭笑疾病除"
  },
  {
    "id": "zhougong-0671",
    "category": "哀樂病死歌唱",
    "original": "病人起者必定死"
  },
  {
    "id": "zhougong-0672",
    "category": "哀樂病死歌唱",
    "original": "病人裝車必死亡"
  },
  {
    "id": "zhougong-0673",
    "category": "哀樂病死歌唱",
    "original": "死人哭泣有口舌"
  },
  {
    "id": "zhougong-0674",
    "category": "哀樂病死歌唱",
    "original": "死人立者主大凶"
  },
  {
    "id": "zhougong-0675",
    "category": "哀樂病死歌唱",
    "original": "死人哭懷者得財"
  },
  {
    "id": "zhougong-0676",
    "category": "哀樂病死歌唱",
    "original": "死人復活主有信"
  },
  {
    "id": "zhougong-0677",
    "category": "哀樂病死歌唱",
    "original": "見人死自死者吉"
  },
  {
    "id": "zhougong-0678",
    "category": "哀樂病死歌唱",
    "original": "子死者有添喜事"
  },
  {
    "id": "zhougong-0679",
    "category": "哀樂病死歌唱",
    "original": "見先亡尊長大吉"
  },
  {
    "id": "zhougong-0680",
    "category": "哀樂病死歌唱",
    "original": "問弔他人主生子"
  },
  {
    "id": "zhougong-0681",
    "category": "佛道僧尼鬼神",
    "original": "諸佛菩薩大吉利"
  },
  {
    "id": "zhougong-0682",
    "category": "佛道僧尼鬼神",
    "original": "法師登座主疾病"
  },
  {
    "id": "zhougong-0683",
    "category": "佛道僧尼鬼神",
    "original": "老君真入皆主吉"
  },
  {
    "id": "zhougong-0684",
    "category": "佛道僧尼鬼神",
    "original": "畫神佛者得人欽"
  },
  {
    "id": "zhougong-0685",
    "category": "佛道僧尼鬼神",
    "original": "入神廟神動大吉"
  },
  {
    "id": "zhougong-0686",
    "category": "佛道僧尼鬼神",
    "original": "造旛蓋者大吉利"
  },
  {
    "id": "zhougong-0687",
    "category": "佛道僧尼鬼神",
    "original": "僧師教人唸經吉"
  },
  {
    "id": "zhougong-0688",
    "category": "佛道僧尼鬼神",
    "original": "道士女冠言語吉"
  },
  {
    "id": "zhougong-0689",
    "category": "佛道僧尼鬼神",
    "original": "和尚尼姑看經悶"
  },
  {
    "id": "zhougong-0690",
    "category": "佛道僧尼鬼神",
    "original": "被神鬼打大不祥"
  },
  {
    "id": "zhougong-0691",
    "category": "佛道僧尼鬼神",
    "original": "堂上神佛大吉利"
  },
  {
    "id": "zhougong-0692",
    "category": "佛道僧尼鬼神",
    "original": "神佛不成形大凶"
  },
  {
    "id": "zhougong-0693",
    "category": "佛道僧尼鬼神",
    "original": "燒香禮拜皆大吉"
  },
  {
    "id": "zhougong-0694",
    "category": "佛道僧尼鬼神",
    "original": "迎神賽社有外財"
  },
  {
    "id": "zhougong-0695",
    "category": "佛道僧尼鬼神",
    "original": "仙聖到家福祿至"
  },
  {
    "id": "zhougong-0696",
    "category": "佛道僧尼鬼神",
    "original": "與鬼鬥者主延壽"
  },
  {
    "id": "zhougong-0697",
    "category": "佛道僧尼鬼神",
    "original": "祭祀神道大吉利"
  },
  {
    "id": "zhougong-0698",
    "category": "佛道僧尼鬼神",
    "original": "身受戒行者子孝"
  },
  {
    "id": "zhougong-0699",
    "category": "佛道僧尼鬼神",
    "original": "與神女通得貴子"
  },
  {
    "id": "zhougong-0700",
    "category": "佛道僧尼鬼神",
    "original": "與尼姑交主失財"
  },
  {
    "id": "zhougong-0701",
    "category": "佛道僧尼鬼神",
    "original": "看神佛者妻有子"
  },
  {
    "id": "zhougong-0702",
    "category": "佛道僧尼鬼神",
    "original": "佛共人言有福助"
  },
  {
    "id": "zhougong-0703",
    "category": "被害鬥傷打罵",
    "original": "被人殺害者大吉"
  },
  {
    "id": "zhougong-0704",
    "category": "被害鬥傷打罵",
    "original": "殺死他人大富貴"
  },
  {
    "id": "zhougong-0705",
    "category": "被害鬥傷打罵",
    "original": "持刀自殺者大吉"
  },
  {
    "id": "zhougong-0706",
    "category": "被害鬥傷打罵",
    "original": "殺人血污衣得財"
  },
  {
    "id": "zhougong-0707",
    "category": "被害鬥傷打罵",
    "original": "被刀刺火出快利"
  },
  {
    "id": "zhougong-0708",
    "category": "被害鬥傷打罵",
    "original": "持刀相殺見血吉"
  },
  {
    "id": "zhougong-0709",
    "category": "被害鬥傷打罵",
    "original": "刀傷出血主酒食"
  },
  {
    "id": "zhougong-0710",
    "category": "被害鬥傷打罵",
    "original": "砍刺見血主大吉"
  },
  {
    "id": "zhougong-0711",
    "category": "被害鬥傷打罵",
    "original": "炙身見血流大吉"
  },
  {
    "id": "zhougong-0712",
    "category": "被害鬥傷打罵",
    "original": "刀斧自傷主大吉"
  },
  {
    "id": "zhougong-0713",
    "category": "被害鬥傷打罵",
    "original": "持刀斫人自失財"
  },
  {
    "id": "zhougong-0714",
    "category": "被害鬥傷打罵",
    "original": "人砍頭腦中二吉"
  },
  {
    "id": "zhougong-0715",
    "category": "被害鬥傷打罵",
    "original": "被人打者主得力"
  },
  {
    "id": "zhougong-0716",
    "category": "被害鬥傷打罵",
    "original": "被人腳踢主求財"
  },
  {
    "id": "zhougong-0717",
    "category": "被害鬥傷打罵",
    "original": "打妻妾者主失力"
  },
  {
    "id": "zhougong-0718",
    "category": "被害鬥傷打罵",
    "original": "家中人鬥主分散"
  },
  {
    "id": "zhougong-0719",
    "category": "被害鬥傷打罵",
    "original": "斷頭而行主大喜"
  },
  {
    "id": "zhougong-0720",
    "category": "被害鬥傷打罵",
    "original": "女人相打主病至"
  },
  {
    "id": "zhougong-0721",
    "category": "被害鬥傷打罵",
    "original": "兄弟相打大吉利"
  },
  {
    "id": "zhougong-0722",
    "category": "被害鬥傷打罵",
    "original": "被妻妾打主凶事"
  },
  {
    "id": "zhougong-0723",
    "category": "被害鬥傷打罵",
    "original": "看見殺人主大吉"
  },
  {
    "id": "zhougong-0724",
    "category": "被害鬥傷打罵",
    "original": "被人簽刺大吉昌"
  },
  {
    "id": "zhougong-0725",
    "category": "被害鬥傷打罵",
    "original": "手措折者主子病"
  },
  {
    "id": "zhougong-0726",
    "category": "被害鬥傷打罵",
    "original": "向人叩頭百事吉"
  },
  {
    "id": "zhougong-0727",
    "category": "被害鬥傷打罵",
    "original": "與人相罵者主吉"
  },
  {
    "id": "zhougong-0728",
    "category": "被害鬥傷打罵",
    "original": "被罵佯顛大貴至"
  },
  {
    "id": "zhougong-0729",
    "category": "被害鬥傷打罵",
    "original": "被人凌辱主得財"
  },
  {
    "id": "zhougong-0730",
    "category": "被害鬥傷打罵",
    "original": "殺豬豖者大吉利"
  },
  {
    "id": "zhougong-0731",
    "category": "被害鬥傷打罵",
    "original": "殺羊打羊主病凶"
  },
  {
    "id": "zhougong-0732",
    "category": "被害鬥傷打罵",
    "original": "殺虎豹主得重印"
  },
  {
    "id": "zhougong-0733",
    "category": "被害鬥傷打罵",
    "original": "殺牛鹿者大富貴"
  },
  {
    "id": "zhougong-0734",
    "category": "被害鬥傷打罵",
    "original": "殺牛食肉主生財"
  },
  {
    "id": "zhougong-0735",
    "category": "被害鬥傷打罵",
    "original": "殺驢騾馬有酒食"
  },
  {
    "id": "zhougong-0736",
    "category": "被害鬥傷打罵",
    "original": "殺龜者主有喪事"
  },
  {
    "id": "zhougong-0737",
    "category": "被害鬥傷打罵",
    "original": "殺鳥雀妻妾災難"
  },
  {
    "id": "zhougong-0738",
    "category": "被害鬥傷打罵",
    "original": "殺雞鵝鴨主大吉"
  },
  {
    "id": "zhougong-0739",
    "category": "捕禁刑罰獄具",
    "original": "牢獄崩壞有赦吉"
  },
  {
    "id": "zhougong-0740",
    "category": "捕禁刑罰獄具",
    "original": "坐獄中必有恩赦"
  },
  {
    "id": "zhougong-0741",
    "category": "捕禁刑罰獄具",
    "original": "入獄愛災主榮貴"
  },
  {
    "id": "zhougong-0742",
    "category": "捕禁刑罰獄具",
    "original": "獄中死者官事散"
  },
  {
    "id": "zhougong-0743",
    "category": "捕禁刑罰獄具",
    "original": "使人入獄得財吉"
  },
  {
    "id": "zhougong-0744",
    "category": "捕禁刑罰獄具",
    "original": "入牢獄主有大貴"
  },
  {
    "id": "zhougong-0745",
    "category": "捕禁刑罰獄具",
    "original": "盜賊自入獄大凶"
  },
  {
    "id": "zhougong-0746",
    "category": "捕禁刑罰獄具",
    "original": "牢獄臭污百事吉"
  },
  {
    "id": "zhougong-0747",
    "category": "捕禁刑罰獄具",
    "original": "罪人走脫疾病去"
  },
  {
    "id": "zhougong-0748",
    "category": "捕禁刑罰獄具",
    "original": "趕賊行見者大吉"
  },
  {
    "id": "zhougong-0749",
    "category": "捕禁刑罰獄具",
    "original": "枷銷臨身疾病至"
  },
  {
    "id": "zhougong-0750",
    "category": "捕禁刑罰獄具",
    "original": "枷鎖折損口舌散"
  },
  {
    "id": "zhougong-0751",
    "category": "捕禁刑罰獄具",
    "original": "枷鎖入宅主大凶"
  },
  {
    "id": "zhougong-0752",
    "category": "捕禁刑罰獄具",
    "original": "繩索繫身大吉利"
  },
  {
    "id": "zhougong-0753",
    "category": "捕禁刑罰獄具",
    "original": "身被羅網主官事"
  },
  {
    "id": "zhougong-0754",
    "category": "捕禁刑罰獄具",
    "original": "被羅網罩主酒食"
  },
  {
    "id": "zhougong-0755",
    "category": "捕禁刑罰獄具",
    "original": "被人決罰祿位至"
  },
  {
    "id": "zhougong-0756",
    "category": "捕禁刑罰獄具",
    "original": "被人作賤者大吉"
  },
  {
    "id": "zhougong-0757",
    "category": "捕禁刑罰獄具",
    "original": "被人綁住疾病至"
  },
  {
    "id": "zhougong-0758",
    "category": "捕禁刑罰獄具",
    "original": "被官打身主孝服"
  },
  {
    "id": "zhougong-0759",
    "category": "捕禁刑罰獄具",
    "original": "自以杖決恥辱生"
  },
  {
    "id": "zhougong-0760",
    "category": "捕禁刑罰獄具",
    "original": "枷鎖怕怖主分散"
  },
  {
    "id": "zhougong-0761",
    "category": "捕禁刑罰獄具",
    "original": "入官詞訟主大吉"
  },
  {
    "id": "zhougong-0762",
    "category": "捕禁刑罰獄具",
    "original": "邀人入官主大吉"
  },
  {
    "id": "zhougong-0763",
    "category": "捕禁刑罰獄具",
    "original": "吏引入司主大吉"
  },
  {
    "id": "zhougong-0764",
    "category": "捕禁刑罰獄具",
    "original": "為吏所錄有急事"
  },
  {
    "id": "zhougong-0765",
    "category": "捕禁刑罰獄具",
    "original": "貴人走馬官事明"
  },
  {
    "id": "zhougong-0766",
    "category": "捕禁刑罰獄具",
    "original": "拷訊杖責主大吉"
  },
  {
    "id": "zhougong-0767",
    "category": "田園五榖耕種",
    "original": "田中生草主得財"
  },
  {
    "id": "zhougong-0768",
    "category": "田園五榖耕種",
    "original": "種田廣大有祿位"
  },
  {
    "id": "zhougong-0769",
    "category": "田園五榖耕種",
    "original": "自種田禾主出行"
  },
  {
    "id": "zhougong-0770",
    "category": "田園五榖耕種",
    "original": "見種田者祿位至"
  },
  {
    "id": "zhougong-0771",
    "category": "田園五榖耕種",
    "original": "教人耕種遠行至"
  },
  {
    "id": "zhougong-0772",
    "category": "田園五榖耕種",
    "original": "使人種田地大吉"
  },
  {
    "id": "zhougong-0773",
    "category": "田園五榖耕種",
    "original": "買人田宅主進職"
  },
  {
    "id": "zhougong-0774",
    "category": "田園五榖耕種",
    "original": "身在禾中大吉利"
  },
  {
    "id": "zhougong-0775",
    "category": "田園五榖耕種",
    "original": "破敗田地主大吉"
  },
  {
    "id": "zhougong-0776",
    "category": "田園五榖耕種",
    "original": "割收田禾家居安"
  },
  {
    "id": "zhougong-0777",
    "category": "田園五榖耕種",
    "original": "屋上生禾官位吉"
  },
  {
    "id": "zhougong-0778",
    "category": "田園五榖耕種",
    "original": "禾苗豊熟富貴長"
  },
  {
    "id": "zhougong-0779",
    "category": "田園五榖耕種",
    "original": "見麥稻主得大財"
  },
  {
    "id": "zhougong-0780",
    "category": "田園五榖耕種",
    "original": "粳精米者有財吉"
  },
  {
    "id": "zhougong-0781",
    "category": "田園五榖耕種",
    "original": "五穀茂盛主得財"
  },
  {
    "id": "zhougong-0782",
    "category": "田園五榖耕種",
    "original": "穀穗齊秀大吉利"
  },
  {
    "id": "zhougong-0783",
    "category": "田園五榖耕種",
    "original": "米谷堆吉散主凶"
  },
  {
    "id": "zhougong-0784",
    "category": "田園五榖耕種",
    "original": "大小麥主妻私心"
  },
  {
    "id": "zhougong-0785",
    "category": "田園五榖耕種",
    "original": "大豆苗葉子孫凶"
  },
  {
    "id": "zhougong-0786",
    "category": "田園五榖耕種",
    "original": "米麥相排大吉利"
  },
  {
    "id": "zhougong-0787",
    "category": "田園五榖耕種",
    "original": "坐臥米麥主大吉"
  },
  {
    "id": "zhougong-0788",
    "category": "田園五榖耕種",
    "original": "手中把榖主福祿"
  },
  {
    "id": "zhougong-0789",
    "category": "田園五榖耕種",
    "original": "得禾榖者主大吉"
  },
  {
    "id": "zhougong-0790",
    "category": "田園五榖耕種",
    "original": "得禾忽失主得志"
  },
  {
    "id": "zhougong-0791",
    "category": "田園五榖耕種",
    "original": "粟米必有獻物至"
  },
  {
    "id": "zhougong-0792",
    "category": "田園五榖耕種",
    "original": "種菜主長命大吉"
  },
  {
    "id": "zhougong-0793",
    "category": "田園五榖耕種",
    "original": "喬麥麵餅官事遷"
  },
  {
    "id": "zhougong-0794",
    "category": "田園五榖耕種",
    "original": "麵糠相交家欲儉"
  },
  {
    "id": "zhougong-0795",
    "category": "田園五榖耕種",
    "original": "涓麴必主枉屈事"
  },
  {
    "id": "zhougong-0796",
    "category": "田園五榖耕種",
    "original": "萌芽者主惡事連"
  },
  {
    "id": "zhougong-0797",
    "category": "田園五榖耕種",
    "original": "麻叢身者主疾至"
  },
  {
    "id": "zhougong-0798",
    "category": "田園五榖耕種",
    "original": "麻生如林大吉利"
  },
  {
    "id": "zhougong-0799",
    "category": "水火盜賊燈燭",
    "original": "水上行者主大吉"
  },
  {
    "id": "zhougong-0800",
    "category": "水火盜賊燈燭",
    "original": "水上立者主凶事"
  },
  {
    "id": "zhougong-0801",
    "category": "水火盜賊燈燭",
    "original": "水流洋洋有新婚"
  },
  {
    "id": "zhougong-0802",
    "category": "水火盜賊燈燭",
    "original": "水上火出主大吉"
  },
  {
    "id": "zhougong-0803",
    "category": "水火盜賊燈燭",
    "original": "自在水中大吉利"
  },
  {
    "id": "zhougong-0804",
    "category": "水火盜賊燈燭",
    "original": "自跌水中不出凶"
  },
  {
    "id": "zhougong-0805",
    "category": "水火盜賊燈燭",
    "original": "飲水不休得大財"
  },
  {
    "id": "zhougong-0806",
    "category": "水火盜賊燈燭",
    "original": "流水遶身有獄訟"
  },
  {
    "id": "zhougong-0807",
    "category": "水火盜賊燈燭",
    "original": "大水澄清大吉利"
  },
  {
    "id": "zhougong-0808",
    "category": "水火盜賊燈燭",
    "original": "人家有水兒子亡"
  },
  {
    "id": "zhougong-0809",
    "category": "水火盜賊燈燭",
    "original": "江海漲漫大吉昌"
  },
  {
    "id": "zhougong-0810",
    "category": "水火盜賊燈燭",
    "original": "河水沙石益文章"
  },
  {
    "id": "zhougong-0811",
    "category": "水火盜賊燈燭",
    "original": "火燒日月有人助"
  },
  {
    "id": "zhougong-0812",
    "category": "水火盜賊燈燭",
    "original": "火燒河水長命吉"
  },
  {
    "id": "zhougong-0813",
    "category": "水火盜賊燈燭",
    "original": "火燒山野大顯達"
  },
  {
    "id": "zhougong-0814",
    "category": "水火盜賊燈燭",
    "original": "火燒自屋主興旺"
  },
  {
    "id": "zhougong-0815",
    "category": "水火盜賊燈燭",
    "original": "火焰炎炎主發財"
  },
  {
    "id": "zhougong-0816",
    "category": "水火盜賊燈燭",
    "original": "火從地生疾病至"
  },
  {
    "id": "zhougong-0817",
    "category": "水火盜賊燈燭",
    "original": "執火乘行官位至"
  },
  {
    "id": "zhougong-0818",
    "category": "水火盜賊燈燭",
    "original": "大火燒天主國安"
  },
  {
    "id": "zhougong-0819",
    "category": "水火盜賊燈燭",
    "original": "身在火中貴人扶"
  },
  {
    "id": "zhougong-0820",
    "category": "水火盜賊燈燭",
    "original": "火煙黑色主疾病"
  },
  {
    "id": "zhougong-0821",
    "category": "水火盜賊燈燭",
    "original": "把火行路大通達"
  },
  {
    "id": "zhougong-0822",
    "category": "水火盜賊燈燭",
    "original": "把火燒井主疾病"
  },
  {
    "id": "zhougong-0823",
    "category": "水火盜賊燈燭",
    "original": "宅中火光大吉利"
  },
  {
    "id": "zhougong-0824",
    "category": "水火盜賊燈燭",
    "original": "廚中火出有急事"
  },
  {
    "id": "zhougong-0825",
    "category": "水火盜賊燈燭",
    "original": "聽選燃火作明府"
  },
  {
    "id": "zhougong-0826",
    "category": "水火盜賊燈燭",
    "original": "燒人臭穢主大吉"
  },
  {
    "id": "zhougong-0827",
    "category": "水火盜賊燈燭",
    "original": "見燭者主大發財"
  },
  {
    "id": "zhougong-0828",
    "category": "水火盜賊燈燭",
    "original": "燈燭光明主大吉"
  },
  {
    "id": "zhougong-0829",
    "category": "水火盜賊燈燭",
    "original": "眾人闈爐和合吉"
  },
  {
    "id": "zhougong-0830",
    "category": "水火盜賊燈燭",
    "original": "惡人相引疾病至"
  },
  {
    "id": "zhougong-0831",
    "category": "水火盜賊燈燭",
    "original": "趕賊入市不出凶"
  },
  {
    "id": "zhougong-0832",
    "category": "水火盜賊燈燭",
    "original": "強賊入宅主家破"
  },
  {
    "id": "zhougong-0833",
    "category": "水火盜賊燈燭",
    "original": "與賊同行大吉利"
  },
  {
    "id": "zhougong-0834",
    "category": "水火盜賊燈燭",
    "original": "己身作賊所求得"
  },
  {
    "id": "zhougong-0835",
    "category": "垢污沐浴凌辱",
    "original": "尿屎污身主得財"
  },
  {
    "id": "zhougong-0836",
    "category": "垢污沐浴凌辱",
    "original": "大便滿地主富貴"
  },
  {
    "id": "zhougong-0837",
    "category": "垢污沐浴凌辱",
    "original": "處廁中得官祿位"
  },
  {
    "id": "zhougong-0838",
    "category": "垢污沐浴凌辱",
    "original": "落廁出吉不出凶"
  },
  {
    "id": "zhougong-0839",
    "category": "垢污沐浴凌辱",
    "original": "廁屋上臥主得財"
  },
  {
    "id": "zhougong-0840",
    "category": "垢污沐浴凌辱",
    "original": "廁中乾者主家破"
  },
  {
    "id": "zhougong-0841",
    "category": "垢污沐浴凌辱",
    "original": "架廁屋主有財喜"
  },
  {
    "id": "zhougong-0842",
    "category": "垢污沐浴凌辱",
    "original": "挑糞回家大吉利"
  },
  {
    "id": "zhougong-0843",
    "category": "垢污沐浴凌辱",
    "original": "在泥中所求不成"
  },
  {
    "id": "zhougong-0844",
    "category": "垢污沐浴凌辱",
    "original": "失大小便主失財"
  },
  {
    "id": "zhougong-0845",
    "category": "垢污沐浴凌辱",
    "original": "污泥衣裳主產凶"
  },
  {
    "id": "zhougong-0846",
    "category": "垢污沐浴凌辱",
    "original": "泥污衫衣主身辱"
  },
  {
    "id": "zhougong-0847",
    "category": "垢污沐浴凌辱",
    "original": "男女沐浴上床凶"
  },
  {
    "id": "zhougong-0848",
    "category": "垢污沐浴凌辱",
    "original": "沐浴塵土疾病安"
  },
  {
    "id": "zhougong-0849",
    "category": "垢污沐浴凌辱",
    "original": "洗頭遷居疾病除"
  },
  {
    "id": "zhougong-0850",
    "category": "垢污沐浴凌辱",
    "original": "被辱罵惹人詞訟"
  },
  {
    "id": "zhougong-0851",
    "category": "龍蛇禽獸等類",
    "original": "乘龍入水有貴位"
  },
  {
    "id": "zhougong-0852",
    "category": "龍蛇禽獸等類",
    "original": "龍眠水中求事遂"
  },
  {
    "id": "zhougong-0853",
    "category": "龍蛇禽獸等類",
    "original": "龍當門者大吉昌"
  },
  {
    "id": "zhougong-0854",
    "category": "龍蛇禽獸等類",
    "original": "龍死亡主失貴位"
  },
  {
    "id": "zhougong-0855",
    "category": "龍蛇禽獸等類",
    "original": "乘龍上山所求遂"
  },
  {
    "id": "zhougong-0856",
    "category": "龍蛇禽獸等類",
    "original": "龍入井中官被辱"
  },
  {
    "id": "zhougong-0857",
    "category": "龍蛇禽獸等類",
    "original": "龍飛有官位大貴"
  },
  {
    "id": "zhougong-0858",
    "category": "龍蛇禽獸等類",
    "original": "乘龍入市主貴位"
  },
  {
    "id": "zhougong-0859",
    "category": "龍蛇禽獸等類",
    "original": "龍蛇入門主得財"
  },
  {
    "id": "zhougong-0860",
    "category": "龍蛇禽獸等類",
    "original": "龍蛇入灶有官至"
  },
  {
    "id": "zhougong-0861",
    "category": "龍蛇禽獸等類",
    "original": "蛇化龍得貴人助"
  },
  {
    "id": "zhougong-0862",
    "category": "龍蛇禽獸等類",
    "original": "婦人見龍生貴子"
  },
  {
    "id": "zhougong-0863",
    "category": "龍蛇禽獸等類",
    "original": "龍蛇殺人主大凶"
  },
  {
    "id": "zhougong-0864",
    "category": "龍蛇禽獸等類",
    "original": "蛇蛟人主得大財"
  },
  {
    "id": "zhougong-0865",
    "category": "龍蛇禽獸等類",
    "original": "蛇入懷中生貴子"
  },
  {
    "id": "zhougong-0866",
    "category": "龍蛇禽獸等類",
    "original": "蛇行水內主榮遷"
  },
  {
    "id": "zhougong-0867",
    "category": "龍蛇禽獸等類",
    "original": "蛇隨人去妻外心"
  },
  {
    "id": "zhougong-0868",
    "category": "龍蛇禽獸等類",
    "original": "蛇入谷道主口舌"
  },
  {
    "id": "zhougong-0869",
    "category": "龍蛇禽獸等類",
    "original": "蛇遶身者生貴子"
  },
  {
    "id": "zhougong-0870",
    "category": "龍蛇禽獸等類",
    "original": "蛇多者主陰司事"
  },
  {
    "id": "zhougong-0871",
    "category": "龍蛇禽獸等類",
    "original": "蛇赤黑口舌青吉"
  },
  {
    "id": "zhougong-0872",
    "category": "龍蛇禽獸等類",
    "original": "蛇黃白主有官事"
  },
  {
    "id": "zhougong-0873",
    "category": "龍蛇禽獸等類",
    "original": "鳳凰主有貴人助"
  },
  {
    "id": "zhougong-0874",
    "category": "龍蛇禽獸等類",
    "original": "鳳集掌上母病至"
  },
  {
    "id": "zhougong-0875",
    "category": "龍蛇禽獸等類",
    "original": "孔雀者主大吉利"
  },
  {
    "id": "zhougong-0876",
    "category": "龍蛇禽獸等類",
    "original": "鶴上天主小口災"
  },
  {
    "id": "zhougong-0877",
    "category": "龍蛇禽獸等類",
    "original": "鶴鳴者祿位大顯"
  },
  {
    "id": "zhougong-0878",
    "category": "龍蛇禽獸等類",
    "original": "鶴入懷中生貴子"
  },
  {
    "id": "zhougong-0879",
    "category": "龍蛇禽獸等類",
    "original": "鶴駕車主征代事"
  },
  {
    "id": "zhougong-0880",
    "category": "龍蛇禽獸等類",
    "original": "放鶴者主得財吉"
  },
  {
    "id": "zhougong-0881",
    "category": "龍蛇禽獸等類",
    "original": "孔雀飛舞有文章"
  },
  {
    "id": "zhougong-0882",
    "category": "龍蛇禽獸等類",
    "original": "鸚鵡婦人主口舌"
  },
  {
    "id": "zhougong-0883",
    "category": "龍蛇禽獸等類",
    "original": "鴛鴦散去主妻凶"
  },
  {
    "id": "zhougong-0884",
    "category": "龍蛇禽獸等類",
    "original": "鳧入宅主有大凶"
  },
  {
    "id": "zhougong-0885",
    "category": "龍蛇禽獸等類",
    "original": "駕鷂者主祿位至"
  },
  {
    "id": "zhougong-0886",
    "category": "龍蛇禽獸等類",
    "original": "鳩鳴者婦人口舌"
  },
  {
    "id": "zhougong-0887",
    "category": "龍蛇禽獸等類",
    "original": "燕飛入懷妻貴子"
  },
  {
    "id": "zhougong-0888",
    "category": "龍蛇禽獸等類",
    "original": "燕子至有遠客來"
  },
  {
    "id": "zhougong-0889",
    "category": "龍蛇禽獸等類",
    "original": "空中鳥鳴主妻亡"
  },
  {
    "id": "zhougong-0890",
    "category": "龍蛇禽獸等類",
    "original": "飛鳥入懷皆主吉"
  },
  {
    "id": "zhougong-0891",
    "category": "龍蛇禽獸等類",
    "original": "捉住飛鳥遠信至"
  },
  {
    "id": "zhougong-0892",
    "category": "龍蛇禽獸等類",
    "original": "雀鼠爭鬥有官事"
  },
  {
    "id": "zhougong-0893",
    "category": "龍蛇禽獸等類",
    "original": "鴉雀相噪主酒食"
  },
  {
    "id": "zhougong-0894",
    "category": "龍蛇禽獸等類",
    "original": "鵝鴨同游添好妾"
  },
  {
    "id": "zhougong-0895",
    "category": "龍蛇禽獸等類",
    "original": "鳥赴蛇來人引薦"
  },
  {
    "id": "zhougong-0896",
    "category": "龍蛇禽獸等類",
    "original": "洗雞得官鳴口舌"
  },
  {
    "id": "zhougong-0897",
    "category": "龍蛇禽獸等類",
    "original": "雞抱卵主有大喜"
  },
  {
    "id": "zhougong-0898",
    "category": "龍蛇禽獸等類",
    "original": "雞在樹上主得財"
  },
  {
    "id": "zhougong-0899",
    "category": "龍蛇禽獸等類",
    "original": "麒麟者名震天下"
  },
  {
    "id": "zhougong-0900",
    "category": "龍蛇禽獸等類",
    "original": "白象江豬官位至"
  },
  {
    "id": "zhougong-0901",
    "category": "龍蛇禽獸等類",
    "original": "獅子叫吼聲名震"
  },
  {
    "id": "zhougong-0902",
    "category": "龍蛇禽獸等類",
    "original": "猛虎大吼主得官"
  },
  {
    "id": "zhougong-0903",
    "category": "龍蛇禽獸等類",
    "original": "騎虎行者無惡事"
  },
  {
    "id": "zhougong-0904",
    "category": "龍蛇禽獸等類",
    "original": "虎入宅中官職重"
  },
  {
    "id": "zhougong-0905",
    "category": "龍蛇禽獸等類",
    "original": "虎狼不動見官吉"
  },
  {
    "id": "zhougong-0906",
    "category": "龍蛇禽獸等類",
    "original": "豹狼惡狗有盜賊"
  },
  {
    "id": "zhougong-0907",
    "category": "龍蛇禽獸等類",
    "original": "狼啖腳者主不得"
  },
  {
    "id": "zhougong-0908",
    "category": "龍蛇禽獸等類",
    "original": "駱駝豹豸得重印"
  },
  {
    "id": "zhougong-0909",
    "category": "龍蛇禽獸等類",
    "original": "熊羆主身生貴子"
  },
  {
    "id": "zhougong-0910",
    "category": "龍蛇禽獸等類",
    "original": "群兔上天得貴位"
  },
  {
    "id": "zhougong-0911",
    "category": "龍蛇禽獸等類",
    "original": "獐鹿在家得官祿"
  },
  {
    "id": "zhougong-0912",
    "category": "龍蛇禽獸等類",
    "original": "活兔在園百憂去"
  },
  {
    "id": "zhougong-0913",
    "category": "龍蛇禽獸等類",
    "original": "貓捕鼠者大得財"
  },
  {
    "id": "zhougong-0914",
    "category": "龍蛇禽獸等類",
    "original": "白鼠引路人提攜"
  },
  {
    "id": "zhougong-0915",
    "category": "龍蛇禽獸等類",
    "original": "鼠咬人衣所求得"
  },
  {
    "id": "zhougong-0916",
    "category": "龍蛇禽獸等類",
    "original": "鼠大走主有喜事"
  },
  {
    "id": "zhougong-0917",
    "category": "龍蛇禽獸等類",
    "original": "山猴主有爭訟端"
  },
  {
    "id": "zhougong-0918",
    "category": "龍蛇禽獸等類",
    "original": "白猴主有祿位得"
  },
  {
    "id": "zhougong-0919",
    "category": "牛馬豬羊六畜",
    "original": "黃牛來家主富貴"
  },
  {
    "id": "zhougong-0920",
    "category": "牛馬豬羊六畜",
    "original": "水牛主先祖索食"
  },
  {
    "id": "zhougong-0921",
    "category": "牛馬豬羊六畜",
    "original": "牛上山坡大吉昌"
  },
  {
    "id": "zhougong-0922",
    "category": "牛馬豬羊六畜",
    "original": "牽牛上山主富貴"
  },
  {
    "id": "zhougong-0923",
    "category": "牛馬豬羊六畜",
    "original": "牛角有血主三公"
  },
  {
    "id": "zhougong-0924",
    "category": "牛馬豬羊六畜",
    "original": "牛觸人凡事不成"
  },
  {
    "id": "zhougong-0925",
    "category": "牛馬豬羊六畜",
    "original": "牛出門好事立至"
  },
  {
    "id": "zhougong-0926",
    "category": "牛馬豬羊六畜",
    "original": "水牛來家主喪事"
  },
  {
    "id": "zhougong-0927",
    "category": "牛馬豬羊六畜",
    "original": "牛生犢所求皆得"
  },
  {
    "id": "zhougong-0928",
    "category": "牛馬豬羊六畜",
    "original": "騎牛入城有喜臨"
  },
  {
    "id": "zhougong-0929",
    "category": "牛馬豬羊六畜",
    "original": "馬舞庭前凶事散"
  },
  {
    "id": "zhougong-0930",
    "category": "牛馬豬羊六畜",
    "original": "牽牛羊來家歡樂"
  },
  {
    "id": "zhougong-0931",
    "category": "牛馬豬羊六畜",
    "original": "馬行千里大喜至"
  },
  {
    "id": "zhougong-0932",
    "category": "牛馬豬羊六畜",
    "original": "乘馬快吉鈍主凶"
  },
  {
    "id": "zhougong-0933",
    "category": "牛馬豬羊六畜",
    "original": "走馬來往文書事"
  },
  {
    "id": "zhougong-0934",
    "category": "牛馬豬羊六畜",
    "original": "馬駝錢物失祿位"
  },
  {
    "id": "zhougong-0935",
    "category": "牛馬豬羊六畜",
    "original": "馬入室主奸情事"
  },
  {
    "id": "zhougong-0936",
    "category": "牛馬豬羊六畜",
    "original": "披洗放馬皆喜事"
  },
  {
    "id": "zhougong-0937",
    "category": "牛馬豬羊六畜",
    "original": "群馬奔遠百凶解"
  },
  {
    "id": "zhougong-0938",
    "category": "牛馬豬羊六畜",
    "original": "罪人走馬厄事去"
  },
  {
    "id": "zhougong-0939",
    "category": "牛馬豬羊六畜",
    "original": "被馬咬有祿位至"
  },
  {
    "id": "zhougong-0940",
    "category": "牛馬豬羊六畜",
    "original": "乘白馬者主疾病"
  },
  {
    "id": "zhougong-0941",
    "category": "牛馬豬羊六畜",
    "original": "騎驢騾主得財吉"
  },
  {
    "id": "zhougong-0942",
    "category": "牛馬豬羊六畜",
    "original": "殺豬吉豬自死凶"
  },
  {
    "id": "zhougong-0943",
    "category": "牛馬豬羊六畜",
    "original": "豬豚變人官事至"
  },
  {
    "id": "zhougong-0944",
    "category": "牛馬豬羊六畜",
    "original": "羊作豚行行人至"
  },
  {
    "id": "zhougong-0945",
    "category": "牛馬豬羊六畜",
    "original": "豬羊搔癢主口舌"
  },
  {
    "id": "zhougong-0946",
    "category": "牛馬豬羊六畜",
    "original": "騎羊上街主得財"
  },
  {
    "id": "zhougong-0947",
    "category": "牛馬豬羊六畜",
    "original": "子母羊益命大吉"
  },
  {
    "id": "zhougong-0948",
    "category": "牛馬豬羊六畜",
    "original": "犬吠人鬼來求食"
  },
  {
    "id": "zhougong-0949",
    "category": "牛馬豬羊六畜",
    "original": "犬吠主人失財凶"
  },
  {
    "id": "zhougong-0950",
    "category": "牛馬豬羊六畜",
    "original": "屋中生馬主大吉"
  },
  {
    "id": "zhougong-0951",
    "category": "龜鱉魚蝦昆蟲",
    "original": "龜入井宅富貴至"
  },
  {
    "id": "zhougong-0952",
    "category": "龜鱉魚蝦昆蟲",
    "original": "龜蛇相同主生財"
  },
  {
    "id": "zhougong-0953",
    "category": "龜鱉魚蝦昆蟲",
    "original": "見龜者主女人貴"
  },
  {
    "id": "zhougong-0954",
    "category": "龜鱉魚蝦昆蟲",
    "original": "捉龜者主喪事至"
  },
  {
    "id": "zhougong-0955",
    "category": "龜鱉魚蝦昆蟲",
    "original": "見鱉者主有得財"
  },
  {
    "id": "zhougong-0956",
    "category": "龜鱉魚蝦昆蟲",
    "original": "魚飛水上百事散"
  },
  {
    "id": "zhougong-0957",
    "category": "龜鱉魚蝦昆蟲",
    "original": "井內有魚遷官至"
  },
  {
    "id": "zhougong-0958",
    "category": "龜鱉魚蝦昆蟲",
    "original": "張網捕魚大吉利"
  },
  {
    "id": "zhougong-0959",
    "category": "龜鱉魚蝦昆蟲",
    "original": "人捕魚主食皆吉"
  },
  {
    "id": "zhougong-0960",
    "category": "龜鱉魚蝦昆蟲",
    "original": "搶魚食魚主小疾"
  },
  {
    "id": "zhougong-0961",
    "category": "龜鱉魚蝦昆蟲",
    "original": "水中釣魚大吉利"
  },
  {
    "id": "zhougong-0962",
    "category": "龜鱉魚蝦昆蟲",
    "original": "林中魚獵事無成"
  },
  {
    "id": "zhougong-0963",
    "category": "龜鱉魚蝦昆蟲",
    "original": "群魚游水主有財"
  },
  {
    "id": "zhougong-0964",
    "category": "龜鱉魚蝦昆蟲",
    "original": "鯉魚妻有孕大吉"
  },
  {
    "id": "zhougong-0965",
    "category": "龜鱉魚蝦昆蟲",
    "original": "大魚揚動主聲名"
  },
  {
    "id": "zhougong-0966",
    "category": "龜鱉魚蝦昆蟲",
    "original": "小魚生子大吉利"
  },
  {
    "id": "zhougong-0967",
    "category": "龜鱉魚蝦昆蟲",
    "original": "乾魚下水命復通"
  },
  {
    "id": "zhougong-0968",
    "category": "龜鱉魚蝦昆蟲",
    "original": "蝦變魚主失財物"
  },
  {
    "id": "zhougong-0969",
    "category": "龜鱉魚蝦昆蟲",
    "original": "身坐魚蟲病患除"
  },
  {
    "id": "zhougong-0970",
    "category": "龜鱉魚蝦昆蟲",
    "original": "螃蟹主百病消散"
  },
  {
    "id": "zhougong-0971",
    "category": "龜鱉魚蝦昆蟲",
    "original": "蝦蛤鳴走有口舌"
  },
  {
    "id": "zhougong-0972",
    "category": "龜鱉魚蝦昆蟲",
    "original": "水蛭主女人失財"
  },
  {
    "id": "zhougong-0973",
    "category": "龜鱉魚蝦昆蟲",
    "original": "螺螄主在外不利"
  },
  {
    "id": "zhougong-0974",
    "category": "龜鱉魚蝦昆蟲",
    "original": "蛤蜊主老來生子"
  },
  {
    "id": "zhougong-0975",
    "category": "龜鱉魚蝦昆蟲",
    "original": "飛蛾入燈他人敗"
  },
  {
    "id": "zhougong-0976",
    "category": "龜鱉魚蝦昆蟲",
    "original": "蚤飛不繭主小吉"
  },
  {
    "id": "zhougong-0977",
    "category": "龜鱉魚蝦昆蟲",
    "original": "蜂蝶交戲事不成"
  },
  {
    "id": "zhougong-0978",
    "category": "龜鱉魚蝦昆蟲",
    "original": "蜂螫人腳有財喜"
  },
  {
    "id": "zhougong-0979",
    "category": "龜鱉魚蝦昆蟲",
    "original": "蜣蜋作堆主失財"
  },
  {
    "id": "zhougong-0980",
    "category": "龜鱉魚蝦昆蟲",
    "original": "蜻蜓對飛美人來"
  },
  {
    "id": "zhougong-0981",
    "category": "龜鱉魚蝦昆蟲",
    "original": "促織聲繁有小惱"
  },
  {
    "id": "zhougong-0982",
    "category": "龜鱉魚蝦昆蟲",
    "original": "蝙蝠群飛陰事長"
  },
  {
    "id": "zhougong-0983",
    "category": "龜鱉魚蝦昆蟲",
    "original": "蜈蚣咬人壽命吉"
  },
  {
    "id": "zhougong-0984",
    "category": "龜鱉魚蝦昆蟲",
    "original": "蜓蚰主有小財吉"
  },
  {
    "id": "zhougong-0985",
    "category": "龜鱉魚蝦昆蟲",
    "original": "蚯蚓主田宅大吉"
  },
  {
    "id": "zhougong-0986",
    "category": "龜鱉魚蝦昆蟲",
    "original": "蚊子咬人主有失"
  },
  {
    "id": "zhougong-0987",
    "category": "龜鱉魚蝦昆蟲",
    "original": "蠅汸人衣必有讒"
  },
  {
    "id": "zhougong-0988",
    "category": "龜鱉魚蝦昆蟲",
    "original": "螻蟈主有不明事"
  }
] as const;
